"""The entity axis reaches the surfaces: expand.

Two columns the step 2 surfaces read and write, both nullable with no
default, so the migration is safe under the previous release's code:

- ``entities.ownership_pct``: the share a subsidiary's parent holds in it,
  as a percent. Null on the group parent, on linked counterparties, and
  where nobody has recorded one. The treatment a share implies (full,
  equity, cost) is M2 consolidation and reads the column then.
- ``reports.entity_id``: the entity a report is about, stamped by
  ``create-report`` from here on. Null on a shared-in copy (the sender's
  company stands as a linked row) and on every report from before this
  column, which the reads treat as the group parent's; nothing is
  backfilled because nothing but the parent could have made one.

Autogenerated for ``public``; the same DDL is fanned out to every tenant
schema. Fresh tenants get both from the model.

Revision ID: 0039
Revises: 0038
Create Date: 2026-10-06

"""

import sqlalchemy as sa
from alembic import op

from migrations.extensions.helpers import TenantOps, for_each_tenant_schema

revision = "0039"
down_revision = "0038"
branch_labels = None
depends_on = None

REPORTS_INDEX = "idx_reports_entity"


def upgrade() -> None:
  op.add_column(
    "entities",
    sa.Column("ownership_pct", sa.Numeric(precision=7, scale=4), nullable=True),
  )
  op.add_column("reports", sa.Column("entity_id", sa.String(), nullable=True))
  op.create_index(REPORTS_INDEX, "reports", ["entity_id"])

  def _apply(conn, schema: str) -> None:
    t = TenantOps(conn, schema)
    t.add_column("entities", "ownership_pct", "NUMERIC(7,4)")
    t.add_column("reports", "entity_id", "VARCHAR")
    t.create_index(REPORTS_INDEX, "reports", ["entity_id"])

  for_each_tenant_schema(op.get_bind(), _apply)


def downgrade() -> None:
  def _apply(conn, schema: str) -> None:
    t = TenantOps(conn, schema)
    t.drop_index(REPORTS_INDEX)
    t.drop_column("reports", "entity_id")
    t.drop_column("entities", "ownership_pct")

  for_each_tenant_schema(op.get_bind(), _apply)
  op.drop_index(REPORTS_INDEX, table_name="reports")
  op.drop_column("reports", "entity_id")
  op.drop_column("entities", "ownership_pct")
