"""Ownership share on the entity: expand.

A subsidiary records the share its parent holds in it (``ownership_pct``,
a percent). Null on the group parent, on linked counterparties, and where
nobody has recorded one; the treatment a share implies (full, equity, cost)
is M2 consolidation and reads the column then. Nullable, no default, so it
is safe under the previous release's code.

Autogenerated for ``public``; the same ``ALTER`` is fanned out to every
tenant schema. Fresh tenants get the column from the model.

Revision ID: 0039
Revises: 0038
Create Date: 2026-10-06

"""

import sqlalchemy as sa
from alembic import op

from migrations.extensions.helpers import TenantOps, for_each_tenant_schema

revision = "0039"
down_revision = "0038"
branch_labels = None
depends_on = None


def upgrade() -> None:
  op.add_column(
    "entities",
    sa.Column("ownership_pct", sa.Numeric(precision=7, scale=4), nullable=True),
  )

  def _apply(conn, schema: str) -> None:
    TenantOps(conn, schema).add_column("entities", "ownership_pct", "NUMERIC(7,4)")

  for_each_tenant_schema(op.get_bind(), _apply)


def downgrade() -> None:
  def _apply(conn, schema: str) -> None:
    TenantOps(conn, schema).drop_column("entities", "ownership_pct")

  for_each_tenant_schema(op.get_bind(), _apply)
  op.drop_column("entities", "ownership_pct")
