"""`events.document_id`: the stored document an event rests on.

An invoice, a vendor bill, a receipt or a statement is a platform `documents`
row; the event it backs names it. A column rather than a metadata key,
because a source sync owns an event's metadata: a QuickBooks re-sync of an
edited transaction replaces a captured event's metadata outright, and a key
the sync does not send raises a reconciling item on a committed one.

Statement balances (`balance_observed`) named their document in metadata;
they are backfilled here, so the column is the one place a citation lives.
Their metadata keeps the key it had, as the record of what was written then.

Autogenerated (add_column + create_index on `events`), then fanned out to
every tenant schema; autogenerate also reported long-standing drift on
unrelated tables, which is left out.

Revision ID: 0043
Revises: 0042
Create Date: 2026-10-09
"""

from __future__ import annotations

from alembic import op
from sqlalchemy import text
from sqlalchemy.engine import Connection

from migrations.extensions.helpers import TenantOps, for_each_tenant_schema

# revision identifiers, used by Alembic.
revision = "0043"
down_revision = "0042"
branch_labels = None
depends_on = None

_INDEX = "idx_events_document"


def _add(conn: Connection, schema: str) -> None:
  t = TenantOps(conn, schema)
  t.add_column("events", "document_id", "VARCHAR")
  t.create_index(_INDEX, "events", ["document_id"], where="document_id IS NOT NULL")
  conn.execute(
    text(
      f"UPDATE \"{schema}\".events SET document_id = metadata->>'document_id' "
      "WHERE event_type = 'balance_observed' AND document_id IS NULL "
      "AND metadata->>'document_id' IS NOT NULL"
    )
  )


def _drop(conn: Connection, schema: str) -> None:
  # Statement balances recorded after the upgrade name their document only
  # here; put it back where the earlier code reads it.
  conn.execute(
    text(
      f'UPDATE "{schema}".events '
      "SET metadata = metadata || jsonb_build_object('document_id', document_id) "
      "WHERE event_type = 'balance_observed' AND document_id IS NOT NULL"
    )
  )
  t = TenantOps(conn, schema)
  t.drop_index(_INDEX)
  t.drop_column("events", "document_id")


def upgrade() -> None:
  conn = op.get_bind()
  _add(conn, "public")
  for_each_tenant_schema(conn, _add)


def downgrade() -> None:
  conn = op.get_bind()
  _drop(conn, "public")
  for_each_tenant_schema(conn, _drop)
