apiVersion: 1

datasources:
  - name: CloudWatch
    type: cloudwatch
    access: proxy
    uid: cloudwatch
    isDefault: false
    editable: true
    jsonData:
      authType: default
      defaultRegion: us-east-1
      assumeRoleArn: ""
      externalId: ""
      profile: ""
      endpoint: ""
      customMetricsNamespaces: "AWS/ECS,AWS/ApplicationELB,AWS/RDS,AWS/ElastiCache,CWAgent"
      logGroups: ""
    secureJsonData: {}
    version: 1