{
 "title": "${SYSTEM_NAME} Non-Production Dashboard",
 "tags": [
  "${SYSTEM_NAME_LOWER}",
  "staging",
  "infrastructure",
  "ci"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "aws_region", "label": "AWS Region", "query": "us-east-1" }
  ]
 },
 "panels": [
  { "title": " ", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# GitHub Actions Runner" } },
  {
   "title": "GHA Runner CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": {
      "AutoScalingGroupName": "RoboSystemsGHARunner-gha-runner-asg"
     },
     "label": "ASG",
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": { "cpu": "cpu-total", "host": "*" },
     "metricName": "cpu_usage_user",
     "namespace": "RoboSystemsGHARunner/ci",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "GHA Runner Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "host": "*" },
     "metricName": "mem_used_percent",
     "namespace": "RoboSystemsGHARunner/ci",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "GHA Runner Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "host": "*", "path": "/" },
     "metricName": "disk_used_percent",
     "namespace": "RoboSystemsGHARunner/ci",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "GHA Runner Network Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": {
      "AutoScalingGroupName": "RoboSystemsGHARunner-gha-runner-asg"
     },
     "label": "Network In",
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "AutoScalingGroupName": "RoboSystemsGHARunner-gha-runner-asg"
     },
     "label": "Network Out",
     "metricName": "NetworkOut",
     "namespace": "AWS/EC2",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  { "title": " ", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 23 }, "options": { "content": "# Observability Metrics" } },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(endpoint) (rate(robosystems_api_request_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(endpoint) (rate(robosystems_api_request_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Endpoints by Request Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "topk(15, sum by (endpoint) (rate(robosystems_api_requests_total[5m])))*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests/sec",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(robosystems_api_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Status Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status_code) (rate(robosystems_api_requests_total[5m]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  { "title": " ", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 42 }, "options": { "content": "# App & API Clusters" } },
  {
   "title": "ECS CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": {
      "ClusterName": "robosystems-api-staging-cluster",
      "ServiceName": "robosystems-api-staging-service"
     },
     "label": "RoboSystems API",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": { "ClusterName": "roboledger-staging-cluster", "ServiceName": "roboledger-staging-service" },
     "label": "RoboLedger",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": { "ClusterName": "roboinvestor-staging-cluster", "ServiceName": "roboinvestor-staging-service" },
     "label": "RoboInvestor",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "ClusterName": "robosystems-app-staging-cluster",
      "ServiceName": "robosystems-api-staging-service"
     },
     "label": "RoboSystems App",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ECS Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": {
      "ClusterName": "robosystems-api-staging-cluster",
      "ServiceName": "robosystems-api-staging-service"
     },
     "label": "RoboSystems API",
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": { "ClusterName": "roboledger-staging-cluster", "ServiceName": "roboledger-staging-service" },
     "label": "RoboLedger",
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": { "ClusterName": "roboinvestor-staging-cluster", "ServiceName": "roboinvestor-staging-service" },
     "label": "RoboInvestor",
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "ClusterName": "robosystems-app-staging-cluster",
      "ServiceName": "robosystems-app-staging-service"
     },
     "label": "RoboSystems App",
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  { "title": " ", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 54 }, "options": { "content": "# Worker Clusters" } },
  {
   "title": "Worker CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": {
      "ClusterName": "robosystems-worker-default-staging-cluster",
      "ServiceName": "robosystems-worker-default-staging-service"
     },
     "label": "Default",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "ClusterName": "robosystems-worker-critical-staging-cluster",
      "ServiceName": "robosystems-worker-critical-staging-service"
     },
     "label": "Critical",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "ClusterName": "robosystems-worker-shared-extraction-staging-cluster",
      "ServiceName": "robosystems-worker-shared-extraction-staging-service"
     },
     "label": "Shared Extraction",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "ClusterName": "robosystems-worker-shared-processing-staging-cluster",
      "ServiceName": "robosystems-worker-shared-processing-staging-service"
     },
     "label": "Shared Processing",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "ClusterName": "robosystems-worker-shared-ingestion-staging-cluster",
      "ServiceName": "robosystems-worker-shared-ingestion-staging-service"
     },
     "label": "Shared Ingestion",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "ClusterName": "robosystems-worker-maintenance-staging-cluster"
     },
     "expression": "SELECT AVG(CPUUtilization) FROM SCHEMA(\"AWS/ECS\", ClusterName,ServiceName) WHERE ClusterName = 'robosystems-beat-staging-cluster'",
     "label": "Beat",
     "metricEditorMode": 1,
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "period": "300",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Worker Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": {
      "ClusterName": "robosystems-worker-default-staging-cluster",
      "ServiceName": "robosystems-worker-default-staging-service"
     },
     "label": "Default",
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "ClusterName": "robosystems-worker-critical-staging-cluster",
      "ServiceName": "robosystems-worker-critical-staging-service"
     },
     "label": "Critical",
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "ClusterName": "robosystems-worker-shared-extraction-staging-cluster",
      "ServiceName": "robosystems-worker-shared-extraction-staging-service"
     },
     "label": "Shared Extraction",
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "ClusterName": "robosystems-worker-shared-processing-staging-cluster",
      "ServiceName": "robosystems-worker-shared-processing-staging-service"
     },
     "label": "Shared Processing",
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "ClusterName": "robosystems-worker-shared-ingestion-staging-cluster",
      "ServiceName": "robosystems-worker-shared-ingestion-staging-service"
     },
     "label": "Shared Ingestion",
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "ClusterName": "robosystems-beat-staging-cluster",
      "ServiceName": "robosystems-beat-staging-service"
     },
     "label": "Beat",
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Celery Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "Environment": "staging", "Queue": "default" },
     "label": "Default",
     "metricName": "QueueSize",
     "namespace": "RoboSystemsCelery",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": { "Environment": "staging", "Queue": "critical" },
     "label": "Critical",
     "metricName": "QueueSize",
     "namespace": "RoboSystemsCelery",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": { "Environment": "staging", "Queue": "shared-extraction" },
     "label": "Shared Extraction",
     "metricName": "QueueSize",
     "namespace": "RoboSystemsCelery",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": { "Environment": "staging", "Queue": "shared-processing" },
     "label": "Shared Processing",
     "metricName": "QueueSize",
     "namespace": "RoboSystemsCelery",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": { "Environment": "staging", "Queue": "shared-ingestion" },
     "label": "Shared Ingestion",
     "metricName": "QueueSize",
     "namespace": "RoboSystemsCelery",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": { "Environment": "staging", "Queue": "dead_letter" },
     "label": "DLQ",
     "metricName": "QueueSize",
     "namespace": "RoboSystemsCelery",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  { "title": " ", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 66 }, "options": { "content": "# Kuzu Clusters" } },
  {
   "title": "Kuzu CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "InstanceId": "*", "cpu": "cpu-total" },
     "metricName": "CPU_USAGE_ACTIVE",
     "namespace": "RoboSystemsKuzu/Staging",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "AutoScalingGroupName": "RoboSystemsKuzuWritersStandardStaging-writers-asg"
     },
     "label": "ASG",
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Kuzu Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "metricName": "mem_used_percent",
     "namespace": "RoboSystemsKuzu/Staging",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Kuzu Disk Used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "InstanceId": "*", "path": "/mnt/kuzu-data" },
     "metricName": "DISK_USED_PERCENT",
     "namespace": "RoboSystemsKuzu/Staging",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Kuzu Network Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": {
      "AutoScalingGroupName": "RoboSystemsKuzuWritersStandardStaging-writers-asg"
     },
     "label": "Network In",
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "AutoScalingGroupName": "RoboSystemsKuzuWritersStandardStaging-writers-asg"
     },
     "label": "Network Out",
     "metricName": "NetworkOut",
     "namespace": "AWS/EC2",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  { "title": " ", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 89 }, "options": { "content": "# RDS Postgres" } },
  {
   "title": "RDS CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "robosystems-iam-staging" },
     "label": "CPU Utilization",
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RDS Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "robosystems-iam-staging" },
     "label": "Free Memory",
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RDS Storage Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "robosystems-iam-staging" },
     "label": "Free Storage",
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RDS Database Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "robosystems-iam-staging" },
     "label": "Database Connections",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  { "title": " ", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 112 }, "options": { "content": "# Valkey ElastiCache" } },
  {
   "title": "Valkey CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "robosystems-staging-valkey-001" },
     "label": "CPU Utilization",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ElastiCache",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Valkey Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "robosystems-staging-valkey-001" },
     "label": "Memory Utilization",
     "metricName": "DatabaseMemoryUsagePercentage",
     "namespace": "AWS/ElastiCache",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  }
 ]
}