"""Guards for the per-tenant rs-gaap exclusion artifact (MVP-core copy-filter).

The artifact (``frameworks/rs-gaap/tenant-exclude/v1.json``,
generated by ``scripts/generate_tenant_exclude.py``) lists rs-gaap concepts the
public→tenant copy omits. These DB-free tests pin the contract the copy path
relies on and regression-guard the one-way hazard: a rollup-/rule-critical
concept must never appear in the exclusion set (dropping one silently breaks the
render ancestor-rollup or rule binding).

MVP-core curation (Sprint 3) drops the general-special **leaf** level — the
finest disaggregation detail, inert until the granularity-selection feature
ships — while keeping the high-level aggregates. The invariant that matters:
keep the aggregate (a parent in the lattice), drop its leaf detail; add
disaggregation back later via resync.
"""

from __future__ import annotations

import pytest

from robosystems.operations.operators.implementations.mapping.constants import (
  RS_GAAP_SYNTHESIZED_DETAIL_ALLOW,
)
from robosystems.taxonomy.writer import _tenant_exclude_qnames


@pytest.mark.unit
def test_artifact_loads_and_is_nonempty() -> None:
  excluded = _tenant_exclude_qnames()
  assert isinstance(excluded, tuple)
  assert len(excluded) > 0
  assert all(q.startswith("rs-gaap:") for q in excluded)


@pytest.mark.unit
def test_keep_critical_concepts_are_never_excluded() -> None:
  """The render/rule machinery binds these; they must stay in every tenant.
  ``ComprehensiveIncomeNetOfTax`` is the load-bearing case — it is not in the
  default style's render networks (so it looks 'disconnected') but the CI=NI+OCI
  fac-identity targets it, so the generator's rule-ref keep-critical must protect
  it."""
  excluded = set(_tenant_exclude_qnames())
  for qname in (
    "rs-gaap:Assets",
    "rs-gaap:Liabilities",
    "rs-gaap:StockholdersEquity",
    "rs-gaap:LiabilitiesAndStockholdersEquity",
    "rs-gaap:NetIncomeLoss",
    "rs-gaap:ComprehensiveIncomeNetOfTax",
    "rs-gaap:OtherComprehensiveIncomeLossNetOfTax",
  ):
    assert qname not in excluded, (
      f"{qname} is rollup/rule-critical — must not be excluded"
    )


@pytest.mark.unit
def test_clear_cut_categories_present() -> None:
  """Sanity: the exclusion set actually contains the clear-cut targets it
  claims (a dimension member + an industry vertical), so an empty/degenerate
  regeneration doesn't silently pass."""
  excluded = set(_tenant_exclude_qnames())
  assert any(q.endswith(("Member", "Domain")) for q in excluded)
  assert any("OilAndGas" in q for q in excluded)


@pytest.mark.unit
def test_wired_concepts_kept_inert_dropped() -> None:
  """Sharp (keep-critical) policy: a tenant keeps EXACTLY what renders under the
  active Style plus its scaffolding. The 2026-06 split wired the component leaves
  (AccountsPayableCurrent, AccruedLiabilitiesCurrent, Goodwill,
  CashAndCashEquivalentsAtCarryingValue, GeneralAndAdministrativeExpense) into
  the Default Style, so they stay. An aggregate the Style does NOT render
  (``InventoryNet`` — the Style uses ``InventoryNetOfAllowances…``) and leaf
  detail are inert, so they drop; both re-add via resync if a deeper Style wires
  them."""
  excluded = set(_tenant_exclude_qnames())
  for kept in (
    "rs-gaap:AccountsPayableCurrent",
    "rs-gaap:AccruedLiabilitiesCurrent",
    "rs-gaap:Goodwill",
    "rs-gaap:CashAndCashEquivalentsAtCarryingValue",
    "rs-gaap:GeneralAndAdministrativeExpense",
  ):
    assert kept not in excluded, f"{kept} renders under the Default Style — must stay"
  for dropped in (
    "rs-gaap:InventoryNet",  # inert; the Style renders InventoryNetOfAllowances…
    "rs-gaap:AccountsPayableTradeCurrent",
    "rs-gaap:AccruedBonusesCurrent",
    "rs-gaap:AccruedPayrollTaxesCurrent",
  ):
    assert dropped in excluded, f"{dropped} renders nowhere — should be dropped"


@pytest.mark.unit
def test_revenue_cogs_leaves_are_the_modern_concepts() -> None:
  """The IS revenue/COGS rollups were repointed off the us-gaap-deprecated
  leaves (deprecated 2018/2019) onto their modern ASC 606 / ASC 705
  equivalents. The deprecated leaves must now be excluded from tenants (they
  stay in the public mapping mirror) and the modern leaves — the wired calc
  children a CoA maps to — must be kept."""
  excluded = set(_tenant_exclude_qnames())
  for kept in (
    "rs-gaap:RevenueFromContractWithCustomerExcludingAssessedTax",
    "rs-gaap:CostOfGoodsAndServicesSold",
    "rs-gaap:OtherCostOfOperatingRevenue",
  ):
    assert kept not in excluded, f"{kept} is a wired IS leaf — must stay"
  for dropped in (
    "rs-gaap:SalesRevenueNet",
    "rs-gaap:OtherSalesRevenueNet",
    "rs-gaap:CostOfGoodsSold",
    "rs-gaap:CostOfGoodsSoldExcludingDepreciationDepletionAndAmortization",
  ):
    assert dropped in excluded, (
      f"{dropped} is a retired deprecated leaf — should be excluded"
    )


@pytest.mark.unit
def test_synthesized_detail_grains_are_kept() -> None:
  """PP&E Gross + its accumulated-depreciation contra are CoA mapping grains
  (the renderer synthesizes PropertyPlantAndEquipmentNet = Gross - AD and the CF
  Investing derivation reads ΔGross as capex). AD is a general-special leaf, so
  it would be dropped by the leaf-level curation — keep-critical must protect the
  whole RS_GAAP_SYNTHESIZED_DETAIL_ALLOW set, or a tenant can't map fixed assets
  ('not found in library')."""
  excluded = set(_tenant_exclude_qnames())
  for q in RS_GAAP_SYNTHESIZED_DETAIL_ALLOW:
    assert q not in excluded, f"{q} is a synthesized-detail mapping grain — must stay"
