"""Guards for the per-tenant rs-gaap exclusion artifact (Sprint 2 copy-filter).

The artifact (``robosystems/taxonomy/data/tenant_exclude_rs_gaap_v1.json``,
generated by ``scripts/generate_tenant_exclude.py``) lists rs-gaap concepts the
public→tenant copy omits. These DB-free tests pin the contract the copy path
relies on and regression-guard the one-way hazard: a rollup-/rule-critical
concept must never appear in the exclusion set (dropping one silently breaks the
render ancestor-rollup or rule binding).
"""

from __future__ import annotations

import pytest

from robosystems.taxonomy.writer import _tenant_exclude_qnames


@pytest.mark.unit
def test_artifact_loads_and_is_nonempty() -> None:
  excluded = _tenant_exclude_qnames()
  assert isinstance(excluded, tuple)
  assert len(excluded) > 0
  assert all(q.startswith("rs-gaap:") for q in excluded)


@pytest.mark.unit
def test_keep_critical_concepts_are_never_excluded() -> None:
  """The render/rule machinery binds these; they must stay in every tenant.
  ``ComprehensiveIncomeNetOfTax`` is the load-bearing case — it is not in the
  default style's render networks (so it looks 'disconnected') but the CI=NI+OCI
  fac-identity targets it, so the generator's rule-ref keep-critical must protect
  it."""
  excluded = set(_tenant_exclude_qnames())
  for qname in (
    "rs-gaap:Assets",
    "rs-gaap:Liabilities",
    "rs-gaap:StockholdersEquity",
    "rs-gaap:LiabilitiesAndStockholdersEquity",
    "rs-gaap:NetIncomeLoss",
    "rs-gaap:ComprehensiveIncomeNetOfTax",
    "rs-gaap:OtherComprehensiveIncomeLossNetOfTax",
  ):
    assert qname not in excluded, (
      f"{qname} is rollup/rule-critical — must not be excluded"
    )


@pytest.mark.unit
def test_clear_cut_categories_present() -> None:
  """Sanity: the exclusion set actually contains the clear-cut targets it
  claims (a dimension member + an industry vertical), so an empty/degenerate
  regeneration doesn't silently pass."""
  excluded = set(_tenant_exclude_qnames())
  assert any(q.endswith(("Member", "Domain")) for q in excluded)
  assert any("OilAndGas" in q for q in excluded)
