receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    enable_open_metrics: true

  logging:
    loglevel: debug

processors:
  batch:
  filter/healthcheck:
    metrics:
      datapoint:
        - 'attributes["http.route"] == "/v1/status" or attributes["http.route"] == "/status" or attributes["http.route"] == "/health"'

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
    metrics:
      receivers: [otlp]
      processors: [filter/healthcheck, batch]
      exporters: [prometheus, logging]
  telemetry:
    metrics:
      address: 0.0.0.0:8888
