Description: RoboSystems File Storage Service - S3 Buckets and IAM Policies
#
# Bucket Structure:
# - robosystems-shared-raw-{env}      : Raw downloads from external sources (SEC, FRED, BLS)
# - robosystems-shared-processed-{env}: Processed parquet files for graph ingestion
# - robosystems-user-{env}            : User uploads, staging tables, exports
# - robosystems-public-data-{env}     : CloudFront-served public content
# - robosystems-{env}-deployment      : Lambda packages, userdata scripts

Parameters:
  # Environment
  Environment:
    Type: String
    Description: Environment name (e.g., prod, staging)
    Default: prod
    AllowedValues:
      - prod
      - staging
    ConstraintDescription: Must be prod or staging

  # Tagging Configuration
  ServiceTag:
    Type: String
    Description: Service tag for resource identification and billing
    Default: RoboSystems

  # Domain Configuration for Public CDN
  PublicDomainName:
    Type: String
    Description: Domain name for public data CDN (e.g., public.robosystems.ai)
    Default: ""

  HostedZoneId:
    Type: String
    Description: Route53 Hosted Zone ID for the domain
    Default: ""

Conditions:
  HasCustomDomain: !Not [!Equals [!Ref PublicDomainName, ""]]

Resources:
  # ============================================================================
  # S3 BUCKETS
  # ============================================================================

  # Shared Raw Data Bucket (external source downloads: SEC, FRED, BLS, etc.)
  S3BucketSharedRaw:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: !Sub robosystems-shared-raw-${Environment}
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: false
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToIntelligentTiering
            Status: Enabled
            Transitions:
              - TransitionInDays: 0
                StorageClass: INTELLIGENT_TIERING
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-${Environment}-shared-raw-bucket
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: !Ref ServiceTag
        - Key: Component
          Value: SharedRawData
        - Key: CreatedBy
          Value: CloudFormation

  # Shared Processed Data Bucket (parquet files for graph ingestion)
  S3BucketSharedProcessed:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: !Sub robosystems-shared-processed-${Environment}
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: false
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToIntelligentTiering
            Status: Enabled
            Transitions:
              - TransitionInDays: 0
                StorageClass: INTELLIGENT_TIERING
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-${Environment}-shared-processed-bucket
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: !Ref ServiceTag
        - Key: Component
          Value: SharedProcessedData
        - Key: CreatedBy
          Value: CloudFormation

  # User Data Bucket (user uploads, staging tables, exports)
  S3BucketUserData:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: !Sub robosystems-user-${Environment}
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: false
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          # User staging data expires after 7 days
          - Id: ExpireStagingData
            Status: Enabled
            Prefix: staging/
            ExpirationInDays: 7
          # User exports expire after 30 days
          - Id: ExpireExports
            Status: Enabled
            Prefix: exports/
            ExpirationInDays: 30
          # Everything else transitions to IA after 30 days
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-${Environment}-user-bucket
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: !Ref ServiceTag
        - Key: Component
          Value: UserData
        - Key: CreatedBy
          Value: CloudFormation

  # Public Data Repository Bucket (for all publicly accessible data including SEC textblocks)
  S3BucketPublicData:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: !Sub robosystems-public-data-${Environment}
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: false
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToIntelligentTiering
            Status: Enabled
            Transitions:
              - TransitionInDays: 0
                StorageClass: INTELLIGENT_TIERING
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedMethods:
              - GET
              - HEAD
            AllowedHeaders:
              - "*"
            MaxAge: 3600
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-${Environment}-public-data-bucket
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: !Ref ServiceTag
        - Key: Component
          Value: PublicData
        - Key: CreatedBy
          Value: CloudFormation

  # Bucket Policy for CloudFront OAC Access Only
  S3BucketPublicDataPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3BucketPublicData
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          # Allow CloudFront OAC to read objects
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action:
              - s3:GetObject
            Resource: !Sub ${S3BucketPublicData.Arn}/*
            Condition:
              StringEquals:
                "AWS:SourceArn": !Sub "arn:${AWS::Partition}:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"
          # Deny all non-HTTPS requests
          - Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub ${S3BucketPublicData.Arn}/*
              - !GetAtt S3BucketPublicData.Arn
            Condition:
              Bool:
                "aws:SecureTransport": "false"

  # ACM Certificate for Public Data CDN (conditional)
  PublicDataCertificate:
    Type: AWS::CertificateManager::Certificate
    Condition: HasCustomDomain
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      DomainName: !Ref PublicDomainName
      DomainValidationOptions:
        - DomainName: !Ref PublicDomainName
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-${Environment}-public-data-cert
        - Key: Environment
          Value: !Ref Environment

  # CloudFront Origin Access Identity
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub OAI for Public Data Repository ${Environment}

  # CloudFront Distribution for Public Data Repository
  # Origin Access Control for secure CloudFront -> S3 access
  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${Environment}-public-data-oac"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
        Description: "Origin Access Control for Public Data Repository"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Sub Public Data CDN - ${Environment}
        Enabled: true
        HttpVersion: http2
        PriceClass: PriceClass_100 # US, Canada, Europe (cheapest)
        Aliases: !If
          - HasCustomDomain
          - - !Ref PublicDomainName
          - !Ref AWS::NoValue
        ViewerCertificate: !If
          - HasCustomDomain
          - AcmCertificateArn: !Ref PublicDataCertificate
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2021
          - !Ref AWS::NoValue
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt S3BucketPublicData.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ""
            OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # Managed-CachingOptimized
          ResponseHeadersPolicyId: 5cc3b908-e619-4b99-88e5-2cf7f45965bd # Managed-CORS-with-preflight
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /404.html
            ErrorCachingMinTTL: 300
          - ErrorCode: 403
            ResponseCode: 403
            ResponsePagePath: /403.html
            ErrorCachingMinTTL: 300
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-${Environment}-public-data-cdn
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: !Ref ServiceTag
        - Key: Component
          Value: PublicDataCDN

  # Route53 Record for Public Data CDN (conditional)
  PublicDataDNSRecord:
    Type: AWS::Route53::RecordSet
    Condition: HasCustomDomain
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref PublicDomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFront's hosted zone ID
        EvaluateTargetHealth: false

  # Deployment Bucket (Lambda packages, scripts, etc.)
  S3BucketDeployment:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: !Sub robosystems-${Environment}-deployment
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: false
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldLambdaVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
          - Id: CleanupIncompleteMultipartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-${Environment}-deployment-bucket
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: !Ref ServiceTag
        - Key: Component
          Value: Deployment
        - Key: CreatedBy
          Value: CloudFormation

  # IAM Managed Policy for Graph Writers (read shared data, write sync buckets)
  GraphWriterS3Policy:
    Type: AWS::IAM::ManagedPolicy
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      ManagedPolicyName: !Sub ${AWS::StackName}-graph-writer-s3-policy-${Environment}
      Description: S3 access policy for graph writer instances
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          # Read access to shared data buckets
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - !GetAtt S3BucketSharedRaw.Arn
              - !Sub ${S3BucketSharedRaw.Arn}/*
              - !GetAtt S3BucketSharedProcessed.Arn
              - !Sub ${S3BucketSharedProcessed.Arn}/*
          # Write access to public data bucket
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - !GetAtt S3BucketPublicData.Arn
              - !Sub ${S3BucketPublicData.Arn}/*

  # IAM Managed Policy for Shared Data Pipelines (Dagster, etc.)
  SharedDataWriterPolicy:
    Type: AWS::IAM::ManagedPolicy
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      ManagedPolicyName: !Sub ${AWS::StackName}-shared-data-writer-policy-${Environment}
      Description: S3 access policy for shared data pipelines (Dagster)
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          # Full access to shared raw and processed buckets
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
              - s3:ListBucket
            Resource:
              - !GetAtt S3BucketSharedRaw.Arn
              - !Sub ${S3BucketSharedRaw.Arn}/*
              - !GetAtt S3BucketSharedProcessed.Arn
              - !Sub ${S3BucketSharedProcessed.Arn}/*

  # NOTE: S3 Secret removed in 2026-01 restructure
  # Bucket names are computed from environment in application code.
  # PUBLIC_DATA_CDN_URL is passed via ECS task definition environment variables.

Outputs:
  # Policy ARNs for use by other stacks
  GraphWriterS3PolicyArn:
    Description: ARN of the graph writer S3 policy
    Value: !Ref GraphWriterS3Policy
    Export:
      Name: !Sub ${AWS::StackName}-${Environment}-GraphWriterS3PolicyArn

  # Deployment Bucket Outputs
  DeploymentBucketName:
    Description: Name of the deployment bucket
    Value: !Ref S3BucketDeployment
    Export:
      Name: !Sub ${AWS::StackName}-${Environment}-DeploymentBucketName

  DeploymentBucketArn:
    Description: ARN of the deployment bucket
    Value: !GetAtt S3BucketDeployment.Arn
    Export:
      Name: !Sub ${AWS::StackName}-${Environment}-DeploymentBucketArn

  # Public Data Repository Outputs
  PublicDataBucketName:
    Description: Name of the public data repository bucket
    Value: !Ref S3BucketPublicData
    Export:
      Name: !Sub ${AWS::StackName}-${Environment}-PublicDataBucketName

  PublicDataBucketArn:
    Description: ARN of the public data repository bucket
    Value: !GetAtt S3BucketPublicData.Arn
    Export:
      Name: !Sub ${AWS::StackName}-${Environment}-PublicDataBucketArn

  PublicDataCDNURL:
    Description: CloudFront distribution URL for public data
    Value: !If
      - HasCustomDomain
      - !Sub https://${PublicDomainName}
      - !Sub https://${CloudFrontDistribution.DomainName}
    Export:
      Name: !Sub ${AWS::StackName}-${Environment}-PublicDataCDNURL

  CloudFrontDistributionId:
    Description: CloudFront distribution ID for public data
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub ${AWS::StackName}-${Environment}-CloudFrontDistributionId

  # Shared Raw Bucket Outputs
  SharedRawBucketName:
    Description: Name of the shared raw data bucket
    Value: !Ref S3BucketSharedRaw
    Export:
      Name: !Sub ${AWS::StackName}-${Environment}-SharedRawBucketName

  SharedRawBucketArn:
    Description: ARN of the shared raw data bucket
    Value: !GetAtt S3BucketSharedRaw.Arn
    Export:
      Name: !Sub ${AWS::StackName}-${Environment}-SharedRawBucketArn

  # Shared Processed Bucket Outputs
  SharedProcessedBucketName:
    Description: Name of the shared processed data bucket
    Value: !Ref S3BucketSharedProcessed
    Export:
      Name: !Sub ${AWS::StackName}-${Environment}-SharedProcessedBucketName

  SharedProcessedBucketArn:
    Description: ARN of the shared processed data bucket
    Value: !GetAtt S3BucketSharedProcessed.Arn
    Export:
      Name: !Sub ${AWS::StackName}-${Environment}-SharedProcessedBucketArn

  # User Data Bucket Outputs
  UserDataBucketName:
    Description: Name of the user data bucket
    Value: !Ref S3BucketUserData
    Export:
      Name: !Sub ${AWS::StackName}-${Environment}-UserDataBucketName

  UserDataBucketArn:
    Description: ARN of the user data bucket
    Value: !GetAtt S3BucketUserData.Arn
    Export:
      Name: !Sub ${AWS::StackName}-${Environment}-UserDataBucketArn

  # Shared Data Writer Policy ARN
  SharedDataWriterPolicyArn:
    Description: ARN of the shared data writer S3 policy
    Value: !Ref SharedDataWriterPolicy
    Export:
      Name: !Sub ${AWS::StackName}-${Environment}-SharedDataWriterPolicyArn
