"""
Shared Pydantic schemas and models for API routers.

This module contains reusable request/response models and schemas
that are shared across multiple router modules.
"""

# Import all API models for easy access
from .auth import (
  LoginRequest,
  RegisterRequest,
  AuthResponse,
  SSOTokenResponse,
  SSOExchangeRequest,
  SSOExchangeResponse,
  SSOCompleteRequest,
  PasswordCheckRequest,
  PasswordCheckResponse,
  PasswordPolicyResponse,
  EmailVerificationRequest,
  EmailResendRequest,
  ForgotPasswordRequest,
  ResetPasswordRequest,
  ResetPasswordValidateResponse,
)
from .oauth import (
  OAuthProvider,
  OAuthInitRequest,
  OAuthInitResponse,
  OAuthCallbackRequest,
  OAuthTokens,
  OAuthConnectionUpdate,
)
from .common import (
  ErrorResponse,
  SuccessResponse,
  PaginationInfo,
  HealthStatus,
  CreditCostInfo,
  ErrorCode,
  create_error_response,
  create_pagination_info,
)
from .graphs import (
  MAX_QUERY_LENGTH,
  DEFAULT_QUERY_TIMEOUT,
  GraphMetricsResponse,
  GraphUsageResponse,
  CypherQueryRequest,
  CypherQueryResponse,
  BackupCreateRequest,
  BackupResponse,
  BackupListResponse,
  BackupStatsResponse,
  BackupExportRequest,
  GraphMetadata,
  CreateGraphRequest,
  CreateGraphResponse,
  MCPToolCall,
  MCPQueryRequest,
  MCPToolsResponse,
  MCPToolResult,
  MCPSchemaResponse,
  MCPQueryResponse,
  ProviderType,
  ConnectionBase,
  SECConnectionConfig,
  QuickBooksConnectionConfig,
  PlaidConnectionConfig,
  CreateConnectionRequest,
  ConnectionResponse,
  SyncConnectionRequest,
  LinkTokenRequest,
  ExchangeTokenRequest,
  ConnectionProviderInfo,
  ConnectionOptionsResponse,
  AgentMessage,
  AgentRequest,
  AgentResponse,
  GraphTierCopyOperations,
  GraphTierBackup,
  GraphTierLimits,
  GraphTierInstance,
  GraphTierInfo,
  AvailableGraphTiersResponse,
)
from .user import (
  AccountInfo,
  UserResponse,
  UpdateUserRequest,
  UpdatePasswordRequest,
  GraphInfo,
  UserGraphsResponse,
  CreateAPIKeyRequest,
  APIKeyInfo,
  CreateAPIKeyResponse,
  APIKeysResponse,
  UpdateAPIKeyRequest,
  UserLimitsResponse,
  UserUsageResponse,
  UserGraphSummary,
  UserUsageSummaryResponse,
  UserAnalyticsResponse,
)
from .billing import (
  CreditSummaryResponse,
  CreditTransactionResponse,
  CreditCheckRequest,
  StorageLimitResponse,
  EnhancedCreditTransactionResponse,
  TransactionSummaryResponse,
  DetailedTransactionsResponse,
  RepositoryPlanInfo,
  AvailableRepository,
  AvailableRepositoriesResponse,
  SubscriptionInfo,
  UserSubscriptionsResponse,
  SubscriptionRequest,
  SubscriptionResponse,
  TierUpgradeRequest,
  CreditSummary,
  AddOnCreditInfo,
  CreditsSummaryResponse,
  RepositoryCreditsResponse,
  AllocationResult,
  AllocationResponse,
  CancellationResponse,
  UpgradeSubscriptionRequest,
  GraphSubscriptionTier,
  StorageInfo,
  GraphSubscriptions,
  OfferingRepositoryPlan,
  RepositoryInfo,
  RepositorySubscriptions,
  TokenPricing,
  OperationCosts,
  ServiceOfferingSummary,
  ServiceOfferingsResponse,
)
from .entity_graph import (
  AvailableExtension,
  AvailableExtensionsResponse,
  EntityCreate,
  EntityUpdate,
  EntityResponse,
  EntityListResponse,
  EntityWithGraphResponse,
)

# Explicitly define what models are available for import from this module
__all__ = [
  # Agent models
  "AgentMessage",
  "AgentRequest",
  "AgentResponse",
  # Auth models
  "LoginRequest",
  "RegisterRequest",
  "AuthResponse",
  "SSOTokenResponse",
  "SSOExchangeRequest",
  "SSOExchangeResponse",
  "SSOCompleteRequest",
  "PasswordCheckRequest",
  "PasswordCheckResponse",
  "PasswordPolicyResponse",
  "EmailVerificationRequest",
  "EmailResendRequest",
  "ForgotPasswordRequest",
  "ResetPasswordRequest",
  "ResetPasswordValidateResponse",
  # Common models
  "ErrorResponse",
  "SuccessResponse",
  "PaginationInfo",
  "HealthStatus",
  "CreditCostInfo",
  "ErrorCode",
  "create_error_response",
  "create_pagination_info",
  # Entity models
  "EntityCreate",
  "EntityUpdate",
  "EntityResponse",
  "EntityListResponse",
  "EntityWithGraphResponse",
  "AvailableExtension",
  "AvailableExtensionsResponse",
  # Connection models
  "ProviderType",
  "ConnectionBase",
  "SECConnectionConfig",
  "QuickBooksConnectionConfig",
  "PlaidConnectionConfig",
  "CreateConnectionRequest",
  "ConnectionResponse",
  "SyncConnectionRequest",
  "LinkTokenRequest",
  "ExchangeTokenRequest",
  "ConnectionProviderInfo",
  "ConnectionOptionsResponse",
  # Graph models and constants
  "MAX_QUERY_LENGTH",
  "DEFAULT_QUERY_TIMEOUT",
  "GraphMetricsResponse",
  "GraphUsageResponse",
  "CypherQueryRequest",
  "CypherQueryResponse",
  "BackupCreateRequest",
  "BackupResponse",
  "BackupListResponse",
  "BackupStatsResponse",
  "BackupExportRequest",
  "GraphMetadata",
  "CreateGraphRequest",
  "CreateGraphResponse",
  # MCP models
  "MCPToolCall",
  "MCPQueryRequest",
  "MCPToolsResponse",
  "MCPToolResult",
  "MCPSchemaResponse",
  "MCPQueryResponse",
  # OAuth models
  "OAuthProvider",
  "OAuthInitRequest",
  "OAuthInitResponse",
  "OAuthCallbackRequest",
  "OAuthTokens",
  "OAuthConnectionUpdate",
  # User models
  "AccountInfo",
  "UserResponse",
  "UpdateUserRequest",
  "UpdatePasswordRequest",
  "GraphInfo",
  "UserGraphsResponse",
  "CreateAPIKeyRequest",
  "APIKeyInfo",
  "CreateAPIKeyResponse",
  "APIKeysResponse",
  "UpdateAPIKeyRequest",
  "UserLimitsResponse",
  "UserUsageResponse",
  "UserGraphSummary",
  "UserUsageSummaryResponse",
  "UserAnalyticsResponse",
  # Credit models
  "CreditSummaryResponse",
  "CreditTransactionResponse",
  "CreditCheckRequest",
  "StorageLimitResponse",
  "EnhancedCreditTransactionResponse",
  "TransactionSummaryResponse",
  "DetailedTransactionsResponse",
  # Subscription models
  "RepositoryPlanInfo",
  "AvailableRepository",
  "AvailableRepositoriesResponse",
  "SubscriptionInfo",
  "UserSubscriptionsResponse",
  "SubscriptionRequest",
  "SubscriptionResponse",
  "TierUpgradeRequest",
  "CreditSummary",
  "AddOnCreditInfo",
  "CreditsSummaryResponse",
  "RepositoryCreditsResponse",
  "AllocationResult",
  "AllocationResponse",
  "CancellationResponse",
  # Tier models
  "GraphTierCopyOperations",
  "GraphTierBackup",
  "GraphTierLimits",
  "GraphTierInstance",
  "GraphTierInfo",
  "AvailableGraphTiersResponse",
  # Offering models
  "GraphSubscriptionTier",
  "StorageInfo",
  "GraphSubscriptions",
  "OfferingRepositoryPlan",
  "RepositoryInfo",
  "RepositorySubscriptions",
  "TokenPricing",
  "OperationCosts",
  "ServiceOfferingSummary",
  "ServiceOfferingsResponse",
  # Billing models
  "UpgradeSubscriptionRequest",
]
