"""
Balance sheet canonical concepts.
"""

from .concepts import CanonicalConcept

BALANCE_SHEET_CONCEPTS = (
  CanonicalConcept(
    id="total_assets",
    display_name="Total Assets",
    category="balance_sheet",
    description="Total assets of the entity",
    aliases=("assets",),
    expected_elements=("us-gaap:Assets",),
    period_type="instant",
    balance="debit",
  ),
  CanonicalConcept(
    id="current_assets",
    display_name="Current Assets",
    category="balance_sheet",
    description="Total current assets expected to be converted to cash within one year",
    aliases=("total current assets",),
    expected_elements=("us-gaap:AssetsCurrent",),
    period_type="instant",
    balance="debit",
  ),
  CanonicalConcept(
    id="cash_and_equivalents",
    display_name="Cash and Cash Equivalents",
    category="balance_sheet",
    description="Cash and short-term highly liquid investments",
    aliases=("cash", "cash equivalents", "cash and short-term investments"),
    expected_elements=(
      "us-gaap:CashAndCashEquivalentsAtCarryingValue",
      "us-gaap:CashCashEquivalentsAndShortTermInvestments",
      "us-gaap:Cash",
    ),
    period_type="instant",
    balance="debit",
  ),
  CanonicalConcept(
    id="short_term_investments",
    display_name="Short-Term Investments",
    category="balance_sheet",
    description="Short-term marketable securities and investments",
    aliases=("marketable securities", "trading securities"),
    expected_elements=(
      "us-gaap:ShortTermInvestments",
      "us-gaap:MarketableSecuritiesCurrent",
      "us-gaap:AvailableForSaleSecuritiesDebtSecuritiesCurrent",
    ),
    period_type="instant",
    balance="debit",
  ),
  CanonicalConcept(
    id="accounts_receivable",
    display_name="Accounts Receivable",
    category="balance_sheet",
    description="Amounts owed to the entity by customers",
    aliases=("receivables", "trade receivables", "net receivables"),
    expected_elements=(
      "us-gaap:AccountsReceivableNetCurrent",
      "us-gaap:AccountsReceivableNet",
    ),
    period_type="instant",
    balance="debit",
  ),
  CanonicalConcept(
    id="inventory",
    display_name="Inventory",
    category="balance_sheet",
    description="Inventory of goods available for sale",
    aliases=("inventories", "net inventory"),
    expected_elements=(
      "us-gaap:InventoryNet",
      "us-gaap:InventoryFinishedGoods",
    ),
    period_type="instant",
    balance="debit",
  ),
  CanonicalConcept(
    id="property_plant_equipment",
    display_name="Property, Plant and Equipment",
    category="balance_sheet",
    description="Net property, plant and equipment",
    aliases=("pp&e", "ppe", "fixed assets", "net ppe"),
    expected_elements=(
      "us-gaap:PropertyPlantAndEquipmentNet",
      "us-gaap:PropertyPlantAndEquipmentGross",
    ),
    period_type="instant",
    balance="debit",
  ),
  CanonicalConcept(
    id="goodwill",
    display_name="Goodwill",
    category="balance_sheet",
    description="Goodwill from business acquisitions",
    aliases=(),
    expected_elements=("us-gaap:Goodwill",),
    period_type="instant",
    balance="debit",
  ),
  CanonicalConcept(
    id="intangible_assets",
    display_name="Intangible Assets",
    category="balance_sheet",
    description="Net intangible assets excluding goodwill",
    aliases=("net intangibles",),
    expected_elements=(
      "us-gaap:IntangibleAssetsNetExcludingGoodwill",
      "us-gaap:FiniteLivedIntangibleAssetsNet",
    ),
    period_type="instant",
    balance="debit",
  ),
  CanonicalConcept(
    id="total_liabilities",
    display_name="Total Liabilities",
    category="balance_sheet",
    description="Total liabilities of the entity",
    aliases=("liabilities",),
    expected_elements=("us-gaap:Liabilities",),
    period_type="instant",
    balance="credit",
  ),
  CanonicalConcept(
    id="current_liabilities",
    display_name="Current Liabilities",
    category="balance_sheet",
    description="Total current liabilities due within one year",
    aliases=("total current liabilities",),
    expected_elements=("us-gaap:LiabilitiesCurrent",),
    period_type="instant",
    balance="credit",
  ),
  CanonicalConcept(
    id="long_term_debt",
    display_name="Long-Term Debt",
    category="balance_sheet",
    description="Long-term debt obligations excluding current portion",
    aliases=("non-current debt", "long term borrowings"),
    expected_elements=(
      "us-gaap:LongTermDebtNoncurrent",
      "us-gaap:LongTermDebt",
      "us-gaap:LongTermDebtAndCapitalLeaseObligations",
    ),
    period_type="instant",
    balance="credit",
  ),
  CanonicalConcept(
    id="total_debt",
    display_name="Total Debt",
    category="balance_sheet",
    description="Total short-term and long-term debt",
    aliases=("debt",),
    expected_elements=(
      "us-gaap:DebtAndCapitalLeaseObligations",
      "us-gaap:LongTermDebtAndCapitalLeaseObligationsIncludingCurrentMaturities",
    ),
    period_type="instant",
    balance="credit",
  ),
  CanonicalConcept(
    id="stockholders_equity",
    display_name="Stockholders' Equity",
    category="balance_sheet",
    description="Total stockholders' equity attributable to the entity",
    aliases=("shareholders equity", "total equity", "book value"),
    expected_elements=(
      "us-gaap:StockholdersEquity",
      "us-gaap:StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest",
    ),
    period_type="instant",
    balance="credit",
  ),
  CanonicalConcept(
    id="retained_earnings",
    display_name="Retained Earnings",
    category="balance_sheet",
    description="Accumulated retained earnings or deficit",
    aliases=("accumulated deficit", "retained deficit"),
    expected_elements=("us-gaap:RetainedEarningsAccumulatedDeficit",),
    period_type="instant",
    balance="credit",
  ),
)
