"""Create billing namespace - clean slate

Revision ID: 105b5968ec40
Revises: db62e86988de
Create Date: 2025-11-06 20:21:55.443454

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "105b5968ec40"
down_revision = "db62e86988de"
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "billing_customers",
    sa.Column("user_id", sa.String(), nullable=False),
    sa.Column("stripe_customer_id", sa.String(), nullable=True),
    sa.Column("has_payment_method", sa.Boolean(), nullable=False),
    sa.Column("default_payment_method_id", sa.String(), nullable=True),
    sa.Column("invoice_billing_enabled", sa.Boolean(), nullable=False),
    sa.Column("billing_email", sa.String(), nullable=True),
    sa.Column("billing_contact_name", sa.String(), nullable=True),
    sa.Column("payment_terms", sa.String(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(
      ["user_id"],
      ["users.id"],
    ),
    sa.PrimaryKeyConstraint("user_id"),
    sa.UniqueConstraint("stripe_customer_id"),
  )
  op.create_table(
    "billing_invoices",
    sa.Column("id", sa.String(), nullable=False),
    sa.Column("billing_customer_user_id", sa.String(), nullable=False),
    sa.Column("invoice_number", sa.String(), nullable=False),
    sa.Column("period_start", sa.DateTime(), nullable=False),
    sa.Column("period_end", sa.DateTime(), nullable=False),
    sa.Column("subtotal_cents", sa.Integer(), nullable=False),
    sa.Column("tax_cents", sa.Integer(), nullable=False),
    sa.Column("discount_cents", sa.Integer(), nullable=False),
    sa.Column("total_cents", sa.Integer(), nullable=False),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("stripe_invoice_id", sa.String(), nullable=True),
    sa.Column("sent_at", sa.DateTime(), nullable=True),
    sa.Column("due_date", sa.DateTime(), nullable=True),
    sa.Column("paid_at", sa.DateTime(), nullable=True),
    sa.Column("payment_method", sa.String(), nullable=True),
    sa.Column("payment_reference", sa.String(), nullable=True),
    sa.Column("notes", sa.String(), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(
      ["billing_customer_user_id"],
      ["users.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("invoice_number"),
    sa.UniqueConstraint("stripe_invoice_id"),
  )
  op.create_index(
    "idx_billing_invoice_customer",
    "billing_invoices",
    ["billing_customer_user_id"],
    unique=False,
  )
  op.create_index(
    "idx_billing_invoice_due_date", "billing_invoices", ["due_date"], unique=False
  )
  op.create_index(
    "idx_billing_invoice_period",
    "billing_invoices",
    ["period_start", "period_end"],
    unique=False,
  )
  op.create_index(
    "idx_billing_invoice_status", "billing_invoices", ["status"], unique=False
  )
  op.create_table(
    "billing_subscriptions",
    sa.Column("id", sa.String(), nullable=False),
    sa.Column("billing_customer_user_id", sa.String(), nullable=False),
    sa.Column("resource_type", sa.String(), nullable=False),
    sa.Column("resource_id", sa.String(), nullable=False),
    sa.Column("plan_name", sa.String(), nullable=False),
    sa.Column("billing_interval", sa.String(), nullable=False),
    sa.Column("base_price_cents", sa.Integer(), nullable=False),
    sa.Column("stripe_subscription_id", sa.String(), nullable=True),
    sa.Column("stripe_product_id", sa.String(), nullable=True),
    sa.Column("stripe_price_id", sa.String(), nullable=True),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("started_at", sa.DateTime(), nullable=True),
    sa.Column("current_period_start", sa.DateTime(), nullable=True),
    sa.Column("current_period_end", sa.DateTime(), nullable=True),
    sa.Column("canceled_at", sa.DateTime(), nullable=True),
    sa.Column("ends_at", sa.DateTime(), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(
      ["billing_customer_user_id"],
      ["users.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("stripe_subscription_id"),
  )
  op.create_index(
    "idx_billing_sub_customer",
    "billing_subscriptions",
    ["billing_customer_user_id"],
    unique=False,
  )
  op.create_index(
    "idx_billing_sub_resource",
    "billing_subscriptions",
    ["resource_type", "resource_id"],
    unique=False,
  )
  op.create_index(
    "idx_billing_sub_status", "billing_subscriptions", ["status"], unique=False
  )
  op.create_index(
    "idx_billing_sub_stripe",
    "billing_subscriptions",
    ["stripe_subscription_id"],
    unique=False,
  )
  op.create_table(
    "billing_audit_logs",
    sa.Column("id", sa.String(), nullable=False),
    sa.Column("event_type", sa.String(), nullable=False),
    sa.Column("event_timestamp", sa.DateTime(), nullable=False),
    sa.Column("billing_customer_user_id", sa.String(), nullable=True),
    sa.Column("subscription_id", sa.String(), nullable=True),
    sa.Column("invoice_id", sa.String(), nullable=True),
    sa.Column("event_data", sa.JSON(), nullable=True),
    sa.Column("description", sa.String(), nullable=False),
    sa.Column("actor_user_id", sa.String(), nullable=True),
    sa.Column("actor_type", sa.String(), nullable=False),
    sa.Column("actor_ip", sa.String(), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(
      ["actor_user_id"],
      ["users.id"],
    ),
    sa.ForeignKeyConstraint(
      ["billing_customer_user_id"],
      ["users.id"],
    ),
    sa.ForeignKeyConstraint(
      ["invoice_id"],
      ["billing_invoices.id"],
    ),
    sa.ForeignKeyConstraint(
      ["subscription_id"],
      ["billing_subscriptions.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(
    "idx_billing_audit_actor", "billing_audit_logs", ["actor_user_id"], unique=False
  )
  op.create_index(
    "idx_billing_audit_customer",
    "billing_audit_logs",
    ["billing_customer_user_id"],
    unique=False,
  )
  op.create_index(
    "idx_billing_audit_event_type", "billing_audit_logs", ["event_type"], unique=False
  )
  op.create_index(
    "idx_billing_audit_invoice", "billing_audit_logs", ["invoice_id"], unique=False
  )
  op.create_index(
    "idx_billing_audit_subscription",
    "billing_audit_logs",
    ["subscription_id"],
    unique=False,
  )
  op.create_index(
    "idx_billing_audit_timestamp",
    "billing_audit_logs",
    ["event_timestamp"],
    unique=False,
  )
  op.create_table(
    "billing_invoice_line_items",
    sa.Column("id", sa.String(), nullable=False),
    sa.Column("invoice_id", sa.String(), nullable=False),
    sa.Column("subscription_id", sa.String(), nullable=True),
    sa.Column("resource_type", sa.String(), nullable=False),
    sa.Column("resource_id", sa.String(), nullable=False),
    sa.Column("description", sa.String(), nullable=False),
    sa.Column("quantity", sa.Integer(), nullable=False),
    sa.Column("unit_price_cents", sa.Integer(), nullable=False),
    sa.Column("amount_cents", sa.Integer(), nullable=False),
    sa.Column("period_start", sa.DateTime(), nullable=False),
    sa.Column("period_end", sa.DateTime(), nullable=False),
    sa.Column("line_metadata", sa.JSON(), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(
      ["invoice_id"],
      ["billing_invoices.id"],
    ),
    sa.ForeignKeyConstraint(
      ["subscription_id"],
      ["billing_subscriptions.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(
    "idx_billing_line_item_invoice",
    "billing_invoice_line_items",
    ["invoice_id"],
    unique=False,
  )
  op.create_index(
    "idx_billing_line_item_resource",
    "billing_invoice_line_items",
    ["resource_type", "resource_id"],
    unique=False,
  )
  op.create_index(
    "idx_billing_line_item_subscription",
    "billing_invoice_line_items",
    ["subscription_id"],
    unique=False,
  )
  op.drop_table("graph_subscriptions")
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "graph_subscriptions",
    sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column("graph_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column("plan_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column(
      "status",
      postgresql.ENUM(
        "ACTIVE", "PAST_DUE", "CANCELED", "UNPAID", name="subscriptionstatus"
      ),
      autoincrement=False,
      nullable=False,
    ),
    sa.Column(
      "current_period_start",
      postgresql.TIMESTAMP(timezone=True),
      autoincrement=False,
      nullable=True,
    ),
    sa.Column(
      "current_period_end",
      postgresql.TIMESTAMP(timezone=True),
      autoincrement=False,
      nullable=True,
    ),
    sa.Column(
      "created_at",
      postgresql.TIMESTAMP(timezone=True),
      autoincrement=False,
      nullable=False,
    ),
    sa.Column(
      "updated_at",
      postgresql.TIMESTAMP(timezone=True),
      autoincrement=False,
      nullable=False,
    ),
    sa.ForeignKeyConstraint(
      ["user_id"], ["users.id"], name=op.f("graph_subscriptions_user_id_fkey")
    ),
    sa.PrimaryKeyConstraint("id", name=op.f("graph_subscriptions_pkey")),
  )
  op.drop_index(
    "idx_billing_line_item_subscription", table_name="billing_invoice_line_items"
  )
  op.drop_index(
    "idx_billing_line_item_resource", table_name="billing_invoice_line_items"
  )
  op.drop_index(
    "idx_billing_line_item_invoice", table_name="billing_invoice_line_items"
  )
  op.drop_table("billing_invoice_line_items")
  op.drop_index("idx_billing_audit_timestamp", table_name="billing_audit_logs")
  op.drop_index("idx_billing_audit_subscription", table_name="billing_audit_logs")
  op.drop_index("idx_billing_audit_invoice", table_name="billing_audit_logs")
  op.drop_index("idx_billing_audit_event_type", table_name="billing_audit_logs")
  op.drop_index("idx_billing_audit_customer", table_name="billing_audit_logs")
  op.drop_index("idx_billing_audit_actor", table_name="billing_audit_logs")
  op.drop_table("billing_audit_logs")
  op.drop_index("idx_billing_sub_stripe", table_name="billing_subscriptions")
  op.drop_index("idx_billing_sub_status", table_name="billing_subscriptions")
  op.drop_index("idx_billing_sub_resource", table_name="billing_subscriptions")
  op.drop_index("idx_billing_sub_customer", table_name="billing_subscriptions")
  op.drop_table("billing_subscriptions")
  op.drop_index("idx_billing_invoice_status", table_name="billing_invoices")
  op.drop_index("idx_billing_invoice_period", table_name="billing_invoices")
  op.drop_index("idx_billing_invoice_due_date", table_name="billing_invoices")
  op.drop_index("idx_billing_invoice_customer", table_name="billing_invoices")
  op.drop_table("billing_invoices")
  op.drop_table("billing_customers")
  # ### end Alembic commands ###
