"""Add storage breakdown fields to graph_usage_tracking

Revision ID: 7a35e59fc400
Revises: 105b5968ec40
Create Date: 2025-11-06 22:10:49.231560

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7a35e59fc400"
down_revision = "105b5968ec40"
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column(
    "graph_usage_tracking", sa.Column("files_storage_gb", sa.Float(), nullable=True)
  )
  op.add_column(
    "graph_usage_tracking", sa.Column("tables_storage_gb", sa.Float(), nullable=True)
  )
  op.add_column(
    "graph_usage_tracking", sa.Column("graphs_storage_gb", sa.Float(), nullable=True)
  )
  op.add_column(
    "graph_usage_tracking", sa.Column("subgraphs_storage_gb", sa.Float(), nullable=True)
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column("graph_usage_tracking", "subgraphs_storage_gb")
  op.drop_column("graph_usage_tracking", "graphs_storage_gb")
  op.drop_column("graph_usage_tracking", "tables_storage_gb")
  op.drop_column("graph_usage_tracking", "files_storage_gb")
  # ### end Alembic commands ###
