"""Add payment provider fields and subscription_metadata to billing models

Revision ID: 7a89a1bfab0c
Revises: c4cc411768f2
Create Date: 2025-11-07 13:42:35.852014

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7a89a1bfab0c"
down_revision = "c4cc411768f2"
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  # Add payment_provider as nullable first
  op.add_column(
    "billing_subscriptions", sa.Column("payment_provider", sa.String(), nullable=True)
  )
  # Set default value for existing rows (invoice billing is default)
  op.execute(
    "UPDATE billing_subscriptions SET payment_provider = 'invoice' WHERE payment_provider IS NULL"
  )
  # Now make it NOT NULL
  op.alter_column("billing_subscriptions", "payment_provider", nullable=False)

  op.add_column(
    "billing_subscriptions",
    sa.Column("provider_subscription_id", sa.String(), nullable=True),
  )
  op.add_column(
    "billing_subscriptions",
    sa.Column("provider_customer_id", sa.String(), nullable=True),
  )
  op.add_column(
    "billing_subscriptions",
    sa.Column(
      "subscription_metadata",
      postgresql.JSONB(astext_type=sa.Text()),
      server_default="{}",
      nullable=False,
    ),
  )
  op.create_index(
    "idx_billing_sub_provider",
    "billing_subscriptions",
    ["provider_subscription_id"],
    unique=False,
  )
  op.create_unique_constraint(
    None, "billing_subscriptions", ["provider_subscription_id"]
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_constraint(None, "billing_subscriptions", type_="unique")
  op.drop_index("idx_billing_sub_provider", table_name="billing_subscriptions")
  op.drop_column("billing_subscriptions", "subscription_metadata")
  op.drop_column("billing_subscriptions", "provider_customer_id")
  op.drop_column("billing_subscriptions", "provider_subscription_id")
  op.drop_column("billing_subscriptions", "payment_provider")
  # ### end Alembic commands ###
