"""remove_deprecated_credit_multiplier_field

Revision ID: ebb9b6f57088
Revises: c60644793c3b
Create Date: 2025-11-04 20:17:06.060883

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ebb9b6f57088"
down_revision = "c60644793c3b"
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column("graph_credits", "credit_multiplier")
  op.drop_column("graph_usage_tracking", "credit_multiplier")
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column(
    "graph_usage_tracking",
    sa.Column(
      "credit_multiplier",
      sa.NUMERIC(precision=3, scale=1),
      autoincrement=False,
      nullable=True,
    ),
  )
  op.add_column(
    "graph_credits",
    sa.Column(
      "credit_multiplier",
      sa.NUMERIC(precision=3, scale=1),
      autoincrement=False,
      nullable=False,
    ),
  )
  # ### end Alembic commands ###
