name: Refresh Graph Container
description: Refreshes a single graph database container in-place without replacing the instance (supports Kuzu and Neo4j)

inputs:
  environment:
    description: 'Environment (staging, prod)'
    required: true
  instance-id:
    description: 'EC2 Instance ID to update'
    required: true
  node-type:
    description: 'Node type (writer, shared-writer)'
    required: true
  backend:
    description: 'Graph backend (kuzu, neo4j)'
    required: true
  aws-region:
    description: 'AWS region'
    required: false
    default: 'us-east-1'
  aws-account-id:
    description: 'AWS account ID for ECR URI'
    required: true
  health-check-timeout:
    description: 'Seconds to wait for health check after update'
    required: false
    default: '30'

outputs:
  status:
    description: 'Update status (success/failed)'
    value: ${{ steps.update.outputs.status }}
  instance-id:
    description: 'Instance ID that was updated'
    value: ${{ inputs.instance-id }}

runs:
  using: composite
  steps:
    - name: Update Container on ${{ inputs.instance-id }}
      id: update
      shell: bash
      run: |
        echo "🔄 Updating ${{ inputs.backend }} container on instance ${{ inputs.instance-id }} - ${{ inputs.node-type }}"

        # Get ECR URI
        ECR_URI="${{ inputs.aws-account-id }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/robosystems"

        # Determine container name based on backend
        if [ "${{ inputs.backend }}" == "kuzu" ]; then
          if [ "${{ inputs.node-type }}" == "writer" ]; then
            CONTAINER_NAME="kuzu-writer"
          elif [ "${{ inputs.node-type }}" == "shared-writer" ]; then
            CONTAINER_NAME="kuzu-shared-master"
          else
            CONTAINER_NAME="kuzu-shared-writer"
          fi
        elif [ "${{ inputs.backend }}" == "neo4j" ]; then
          if [ "${{ inputs.node-type }}" == "writer" ]; then
            CONTAINER_NAME="neo4j-writer"
          elif [ "${{ inputs.node-type }}" == "shared-writer" ]; then
            CONTAINER_NAME="neo4j-shared-writer"
          else
            CONTAINER_NAME="neo4j-writer"
          fi
        else
          echo "❌ Unknown backend: ${{ inputs.backend }}"
          echo "status=failed" >> $GITHUB_OUTPUT
          exit 1
        fi

        # Use universal startup script
        STARTUP_SCRIPT="/usr/local/bin/run-graph-container.sh"

        echo "📦 Pulling and updating container: $CONTAINER_NAME (backend: ${{ inputs.backend }})"

        # Send update command
        COMMAND_ID=$(aws ssm send-command \
          --instance-ids "${{ inputs.instance-id }}" \
          --document-name "AWS-RunShellScript" \
          --parameters "commands=[
            \"#!/bin/bash\",
            \"set -e\",
            \"echo \\\"🔄 Starting container refresh for $CONTAINER_NAME\\\"\",
            \"echo \\\"Loading environment variables...\\\"\",
            \"if [ -f /etc/environment ]; then set -a; source /etc/environment; set +a; fi\",
            \"echo \\\"Pulling latest image...\\\"\",
            \"aws ecr get-login-password --region ${{ inputs.aws-region }} | docker login --username AWS --password-stdin ${ECR_URI%/*}\",
            \"docker pull ${ECR_URI}:${{ inputs.environment }}\",
            \"export ECR_IMAGE=\\\"${ECR_URI}:${{ inputs.environment }}\\\"\",
            \"echo \\\"Stopping existing container...\\\"\",
            \"docker stop $CONTAINER_NAME || true\",
            \"docker rm $CONTAINER_NAME || true\",
            \"echo \\\"Starting new container...\\\"\",
            \"$STARTUP_SCRIPT\",
            \"echo \\\"✅ Container updated successfully\\\"\"
          ]" \
          --query "Command.CommandId" \
          --output text \
          --region "${{ inputs.aws-region }}")

        echo "⏳ Waiting for update to complete (Command: ${COMMAND_ID})..."

        # Wait for command execution
        if aws ssm wait command-executed \
          --command-id "${COMMAND_ID}" \
          --instance-id "${{ inputs.instance-id }}" \
          --region "${{ inputs.aws-region }}"; then

          echo "✅ Container update completed successfully"

          # Get the output for logging
          OUTPUT=$(aws ssm get-command-invocation \
            --command-id "${COMMAND_ID}" \
            --instance-id "${{ inputs.instance-id }}" \
            --query "StandardOutputContent" \
            --output text \
            --region "${{ inputs.aws-region }}" 2>/dev/null || echo "")

          if [ -n "$OUTPUT" ]; then
            echo "📝 Update output:"
            echo "$OUTPUT" | head -20
          fi

        else
          echo "❌ Container update failed"

          # Get error details
          ERROR_OUTPUT=$(aws ssm get-command-invocation \
            --command-id "${COMMAND_ID}" \
            --instance-id "${{ inputs.instance-id }}" \
            --query "StandardErrorContent" \
            --output text \
            --region "${{ inputs.aws-region }}" 2>/dev/null || echo "No error details available")

          echo "Error details:"
          echo "$ERROR_OUTPUT"

          echo "status=failed" >> $GITHUB_OUTPUT
          exit 1
        fi

        # Health check
        echo "🏥 Waiting ${{ inputs.health-check-timeout }} seconds for container to stabilize..."
        sleep ${{ inputs.health-check-timeout }}

        echo "🏥 Performing health check..."
        HEALTH_COMMAND=$(aws ssm send-command \
          --instance-ids "${{ inputs.instance-id }}" \
          --document-name "AWS-RunShellScript" \
          --parameters 'commands=["curl -f -s http://localhost:8001/health || echo UNHEALTHY"]' \
          --query "Command.CommandId" \
          --output text \
          --region "${{ inputs.aws-region }}")

        sleep 5

        HEALTH_STATUS=$(aws ssm get-command-invocation \
          --command-id "${HEALTH_COMMAND}" \
          --instance-id "${{ inputs.instance-id }}" \
          --query "StandardOutputContent" \
          --output text \
          --region "${{ inputs.aws-region }}" 2>/dev/null || echo "UNHEALTHY")

        if [[ "$HEALTH_STATUS" == *"UNHEALTHY"* ]]; then
          echo "❌ Health check failed for instance ${{ inputs.instance-id }}"
          echo "status=failed" >> $GITHUB_OUTPUT
          exit 1
        else
          echo "✅ Instance ${{ inputs.instance-id }} is healthy"
          echo "Health response: ${HEALTH_STATUS:0:100}..."
          echo "status=success" >> $GITHUB_OUTPUT
        fi
