"""add entities table

Revision ID: 1eec7fa2156e
Revises: df4774bfb8ea
Create Date: 2026-03-26 18:46:00.135091

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1eec7fa2156e"
down_revision = "df4774bfb8ea"
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "entities",
    sa.Column("id", sa.String(), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("legal_name", sa.String(), nullable=True),
    sa.Column("uri", sa.String(), nullable=True),
    sa.Column("cik", sa.String(), nullable=True),
    sa.Column("ticker", sa.String(), nullable=True),
    sa.Column("exchange", sa.String(), nullable=True),
    sa.Column("sic", sa.String(), nullable=True),
    sa.Column("sic_description", sa.String(), nullable=True),
    sa.Column("category", sa.String(), nullable=True),
    sa.Column("state_of_incorporation", sa.String(), nullable=True),
    sa.Column("fiscal_year_end", sa.String(), nullable=True),
    sa.Column("tax_id", sa.String(), nullable=True),
    sa.Column("lei", sa.String(), nullable=True),
    sa.Column("industry", sa.String(), nullable=True),
    sa.Column("entity_type", sa.String(), nullable=True),
    sa.Column("phone", sa.String(), nullable=True),
    sa.Column("website", sa.String(), nullable=True),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("is_parent", sa.Boolean(), nullable=False),
    sa.Column("parent_entity_id", sa.String(), nullable=True),
    sa.Column("source", sa.String(), nullable=False),
    sa.Column("source_id", sa.String(), nullable=True),
    sa.Column("connection_id", sa.String(), nullable=True),
    sa.Column("address_line1", sa.String(), nullable=True),
    sa.Column("address_city", sa.String(), nullable=True),
    sa.Column("address_state", sa.String(), nullable=True),
    sa.Column("address_postal_code", sa.String(), nullable=True),
    sa.Column("address_country", sa.String(), nullable=True),
    sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("version", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.Column("created_by", sa.String(), nullable=False),
    sa.ForeignKeyConstraint(
      ["parent_entity_id"],
      ["entities.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index("idx_entities_parent", "entities", ["parent_entity_id"], unique=False)
  op.create_index("idx_entities_source", "entities", ["source"], unique=False)
  op.create_index("idx_entities_status", "entities", ["status"], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index("idx_entities_status", table_name="entities")
  op.drop_index("idx_entities_source", table_name="entities")
  op.drop_index("idx_entities_parent", table_name="entities")
  op.drop_table("entities")
  # ### end Alembic commands ###
