"""initial roboledger schema

Revision ID: df4774bfb8ea
Revises:
Create Date: 2026-03-16 12:18:30.553700

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "df4774bfb8ea"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
  # Create generate_prefixed_id function (fallback for non-ORM inserts)
  op.execute("""
        CREATE OR REPLACE FUNCTION public.generate_prefixed_id(prefix TEXT)
        RETURNS TEXT AS $$
        BEGIN
            RETURN prefix || '_' || replace(gen_random_uuid()::text, '-', '');
        END;
        $$ LANGUAGE plpgsql;
    """)

  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "accounts",
    sa.Column("id", sa.String(), nullable=False),
    sa.Column("code", sa.String(), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("description", sa.String(), nullable=True),
    sa.Column("classification", sa.String(), nullable=False),
    sa.Column("sub_classification", sa.String(), nullable=True),
    sa.Column("balance_type", sa.String(), nullable=False),
    sa.Column("parent_id", sa.String(), nullable=True),
    sa.Column("depth", sa.Integer(), nullable=False),
    sa.Column("path", sa.String(), nullable=False),
    sa.Column("currency", sa.String(), nullable=False),
    sa.Column("is_active", sa.Boolean(), nullable=False),
    sa.Column("is_placeholder", sa.Boolean(), nullable=False),
    sa.Column("external_id", sa.String(), nullable=True),
    sa.Column("external_source", sa.String(), nullable=True),
    sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("version", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.Column("created_by", sa.String(), nullable=False),
    sa.CheckConstraint(
      "balance_type IN ('debit', 'credit')", name="check_balance_type"
    ),
    sa.CheckConstraint(
      "classification IN ('asset', 'liability', 'equity', 'revenue', 'expense')",
      name="check_account_classification",
    ),
    sa.ForeignKeyConstraint(
      ["parent_id"],
      ["accounts.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("code"),
  )
  op.create_index(
    "idx_accounts_active",
    "accounts",
    ["is_active"],
    unique=False,
    postgresql_where="is_active = true",
  )
  op.create_index(
    "idx_accounts_classification", "accounts", ["classification"], unique=False
  )
  op.create_index(
    "idx_accounts_external",
    "accounts",
    ["external_id", "external_source"],
    unique=False,
  )
  op.create_index("idx_accounts_parent", "accounts", ["parent_id"], unique=False)
  op.create_table(
    "dimensions",
    sa.Column("id", sa.String(), nullable=False),
    sa.Column("dimension_type", sa.String(), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("value", sa.String(), nullable=False),
    sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("is_active", sa.Boolean(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("dimension_type", "value", name="uq_dimension_type_value"),
  )
  op.create_index("idx_dimensions_type", "dimensions", ["dimension_type"], unique=False)
  op.create_table(
    "fiscal_periods",
    sa.Column("id", sa.String(), nullable=False),
    sa.Column("graph_id", sa.String(), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("start_date", sa.Date(), nullable=False),
    sa.Column("end_date", sa.Date(), nullable=False),
    sa.Column("period_type", sa.String(), nullable=False),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("closed_at", sa.DateTime(), nullable=True),
    sa.Column("closed_by", sa.String(), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.CheckConstraint(
      "status IN ('open', 'closing', 'closed')", name="check_fiscal_period_status"
    ),
    sa.CheckConstraint("start_date < end_date", name="check_fiscal_period_dates"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("graph_id", "name", name="uq_fiscal_period_graph_name"),
    schema="public",
  )
  op.create_index(
    "idx_fiscal_periods_dates",
    "fiscal_periods",
    ["graph_id", "start_date", "end_date"],
    unique=False,
    schema="public",
  )
  op.create_index(
    "idx_fiscal_periods_graph",
    "fiscal_periods",
    ["graph_id"],
    unique=False,
    schema="public",
  )
  op.create_table(
    "report_definitions",
    sa.Column("id", sa.String(), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("description", sa.String(), nullable=True),
    sa.Column("report_type", sa.String(), nullable=False),
    sa.Column("mapping_id", sa.String(), nullable=True),
    sa.Column("period_type", sa.String(), nullable=False),
    sa.Column("comparative", sa.Boolean(), nullable=False),
    sa.Column("graph_report_id", sa.String(), nullable=True),
    sa.Column("last_generated", sa.DateTime(), nullable=True),
    sa.Column("generation_status", sa.String(), nullable=False),
    sa.Column("ai_generated", sa.Boolean(), nullable=False),
    sa.Column("ai_intent", sa.String(), nullable=True),
    sa.Column("ai_workspace_id", sa.String(), nullable=True),
    sa.Column("ai_confidence", sa.Float(), nullable=True),
    sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.Column("created_by", sa.String(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(
    "idx_report_defs_status", "report_definitions", ["generation_status"], unique=False
  )
  op.create_index(
    "idx_report_defs_type", "report_definitions", ["report_type"], unique=False
  )
  op.create_table(
    "transactions",
    sa.Column("id", sa.String(), nullable=False),
    sa.Column("number", sa.String(), nullable=True),
    sa.Column("idempotency_key", sa.String(), nullable=True),
    sa.Column("type", sa.String(), nullable=False),
    sa.Column("category", sa.String(), nullable=True),
    sa.Column("amount", sa.BigInteger(), nullable=False),
    sa.Column("currency", sa.String(), nullable=False),
    sa.Column("date", sa.Date(), nullable=False),
    sa.Column("due_date", sa.Date(), nullable=True),
    sa.Column("merchant_name", sa.String(), nullable=True),
    sa.Column("reference_number", sa.String(), nullable=True),
    sa.Column("description", sa.String(), nullable=True),
    sa.Column("source", sa.String(), nullable=False),
    sa.Column("source_id", sa.String(), nullable=True),
    sa.Column("connection_id", sa.String(), nullable=True),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("posted_at", sa.DateTime(), nullable=True),
    sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("version", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.Column("created_by", sa.String(), nullable=False),
    sa.CheckConstraint(
      "status IN ('pending', 'posted', 'void')", name="check_transaction_status"
    ),
    sa.CheckConstraint("amount >= 0", name="check_transaction_amount"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("idempotency_key"),
  )
  op.create_index(
    "idx_transactions_created", "transactions", ["created_at"], unique=False
  )
  op.create_index("idx_transactions_date", "transactions", ["date"], unique=False)
  op.create_index(
    "idx_transactions_merchant", "transactions", ["merchant_name"], unique=False
  )
  op.create_index("idx_transactions_source", "transactions", ["source"], unique=False)
  op.create_index("idx_transactions_status", "transactions", ["status"], unique=False)
  op.create_index("idx_transactions_type", "transactions", ["type"], unique=False)
  op.create_table(
    "classification_rules",
    sa.Column("id", sa.String(), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("description", sa.String(), nullable=True),
    sa.Column("match_source", sa.String(), nullable=True),
    sa.Column("match_type", sa.String(), nullable=True),
    sa.Column("match_merchant", sa.String(), nullable=True),
    sa.Column("match_category", sa.String(), nullable=True),
    sa.Column("match_min_amount", sa.BigInteger(), nullable=True),
    sa.Column("match_max_amount", sa.BigInteger(), nullable=True),
    sa.Column("target_account_id", sa.String(), nullable=False),
    sa.Column("entry_type", sa.String(), nullable=False),
    sa.Column("debit_account_id", sa.String(), nullable=False),
    sa.Column("credit_account_id", sa.String(), nullable=False),
    sa.Column("dimensions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("suggested_by", sa.String(), nullable=True),
    sa.Column("confidence", sa.Float(), nullable=True),
    sa.Column("approved_by", sa.String(), nullable=True),
    sa.Column("approved_at", sa.DateTime(), nullable=True),
    sa.Column("is_active", sa.Boolean(), nullable=False),
    sa.Column("priority", sa.Integer(), nullable=False),
    sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.Column("created_by", sa.String(), nullable=False),
    sa.ForeignKeyConstraint(
      ["credit_account_id"],
      ["accounts.id"],
    ),
    sa.ForeignKeyConstraint(
      ["debit_account_id"],
      ["accounts.id"],
    ),
    sa.ForeignKeyConstraint(
      ["target_account_id"],
      ["accounts.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(
    "idx_rules_active",
    "classification_rules",
    ["is_active", "priority"],
    unique=False,
    postgresql_where="is_active = true",
  )
  op.create_index(
    "idx_rules_source", "classification_rules", ["match_source"], unique=False
  )
  op.create_table(
    "entries",
    sa.Column("id", sa.String(), nullable=False),
    sa.Column("number", sa.String(), nullable=True),
    sa.Column("idempotency_key", sa.String(), nullable=True),
    sa.Column("transaction_id", sa.String(), nullable=True),
    sa.Column("type", sa.String(), nullable=False),
    sa.Column("reversal_of", sa.String(), nullable=True),
    sa.Column("posting_date", sa.Date(), nullable=False),
    sa.Column("memo", sa.String(), nullable=True),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("posted_at", sa.DateTime(), nullable=True),
    sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("version", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.Column("created_by", sa.String(), nullable=False),
    sa.CheckConstraint(
      "status IN ('draft', 'posted', 'reversed')", name="check_entry_status"
    ),
    sa.CheckConstraint(
      "type IN ('standard', 'adjusting', 'closing', 'reversing')",
      name="check_entry_type",
    ),
    sa.ForeignKeyConstraint(
      ["reversal_of"],
      ["entries.id"],
    ),
    sa.ForeignKeyConstraint(
      ["transaction_id"],
      ["transactions.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("idempotency_key"),
  )
  op.create_index("idx_entries_posting_date", "entries", ["posting_date"], unique=False)
  op.create_index("idx_entries_status", "entries", ["status"], unique=False)
  op.create_index(
    "idx_entries_transaction", "entries", ["transaction_id"], unique=False
  )
  op.create_index("idx_entries_type", "entries", ["type"], unique=False)
  op.create_table(
    "transaction_dimensions",
    sa.Column("transaction_id", sa.String(), nullable=False),
    sa.Column("dimension_id", sa.String(), nullable=False),
    sa.ForeignKeyConstraint(
      ["dimension_id"],
      ["dimensions.id"],
    ),
    sa.ForeignKeyConstraint(
      ["transaction_id"], ["transactions.id"], ondelete="CASCADE"
    ),
    sa.PrimaryKeyConstraint("transaction_id", "dimension_id"),
  )
  op.create_table(
    "entry_dimensions",
    sa.Column("entry_id", sa.String(), nullable=False),
    sa.Column("dimension_id", sa.String(), nullable=False),
    sa.ForeignKeyConstraint(
      ["dimension_id"],
      ["dimensions.id"],
    ),
    sa.ForeignKeyConstraint(["entry_id"], ["entries.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("entry_id", "dimension_id"),
  )
  op.create_table(
    "line_items",
    sa.Column("id", sa.String(), nullable=False),
    sa.Column("entry_id", sa.String(), nullable=False),
    sa.Column("account_id", sa.String(), nullable=False),
    sa.Column("debit_amount", sa.BigInteger(), nullable=False),
    sa.Column("credit_amount", sa.BigInteger(), nullable=False),
    sa.Column("description", sa.String(), nullable=True),
    sa.Column("line_order", sa.Integer(), nullable=False),
    sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.CheckConstraint(
      "NOT (debit_amount > 0 AND credit_amount > 0)", name="check_not_both_amounts"
    ),
    sa.CheckConstraint("credit_amount >= 0", name="check_credit_positive"),
    sa.CheckConstraint(
      "debit_amount > 0 OR credit_amount > 0", name="check_at_least_one_amount"
    ),
    sa.CheckConstraint("debit_amount >= 0", name="check_debit_positive"),
    sa.ForeignKeyConstraint(
      ["account_id"],
      ["accounts.id"],
    ),
    sa.ForeignKeyConstraint(["entry_id"], ["entries.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index("idx_line_items_account", "line_items", ["account_id"], unique=False)
  op.create_index("idx_line_items_entry", "line_items", ["entry_id"], unique=False)
  op.create_table(
    "line_item_dimensions",
    sa.Column("line_item_id", sa.String(), nullable=False),
    sa.Column("dimension_id", sa.String(), nullable=False),
    sa.ForeignKeyConstraint(
      ["dimension_id"],
      ["dimensions.id"],
    ),
    sa.ForeignKeyConstraint(["line_item_id"], ["line_items.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("line_item_id", "dimension_id"),
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table("line_item_dimensions")
  op.drop_index("idx_line_items_entry", table_name="line_items")
  op.drop_index("idx_line_items_account", table_name="line_items")
  op.drop_table("line_items")
  op.drop_table("entry_dimensions")
  op.drop_table("transaction_dimensions")
  op.drop_index("idx_entries_type", table_name="entries")
  op.drop_index("idx_entries_transaction", table_name="entries")
  op.drop_index("idx_entries_status", table_name="entries")
  op.drop_index("idx_entries_posting_date", table_name="entries")
  op.drop_table("entries")
  op.drop_index("idx_rules_source", table_name="classification_rules")
  op.drop_index(
    "idx_rules_active",
    table_name="classification_rules",
    postgresql_where="is_active = true",
  )
  op.drop_table("classification_rules")
  op.drop_index("idx_transactions_type", table_name="transactions")
  op.drop_index("idx_transactions_status", table_name="transactions")
  op.drop_index("idx_transactions_source", table_name="transactions")
  op.drop_index("idx_transactions_merchant", table_name="transactions")
  op.drop_index("idx_transactions_date", table_name="transactions")
  op.drop_index("idx_transactions_created", table_name="transactions")
  op.drop_table("transactions")
  op.drop_index("idx_report_defs_type", table_name="report_definitions")
  op.drop_index("idx_report_defs_status", table_name="report_definitions")
  op.drop_table("report_definitions")
  op.drop_index(
    "idx_fiscal_periods_graph", table_name="fiscal_periods", schema="public"
  )
  op.drop_index(
    "idx_fiscal_periods_dates", table_name="fiscal_periods", schema="public"
  )
  op.drop_table("fiscal_periods", schema="public")
  op.drop_index("idx_dimensions_type", table_name="dimensions")
  op.drop_table("dimensions")
  op.drop_index("idx_accounts_parent", table_name="accounts")
  op.drop_index("idx_accounts_external", table_name="accounts")
  op.drop_index("idx_accounts_classification", table_name="accounts")
  op.drop_index(
    "idx_accounts_active", table_name="accounts", postgresql_where="is_active = true"
  )
  op.drop_table("accounts")
  # ### end Alembic commands ###

  op.execute("DROP FUNCTION IF EXISTS public.generate_prefixed_id(TEXT)")
