{
 "title": "RoboSystems Production Dashboard",
 "tags": [
  "robosystems",
  "infrastructure",
  "prod"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "aws_region", "label": "AWS Region", "query": "us-east-1" },
   { "name": "endpoints", "label": "Endpoints", "query": { "query": "label_values(endpoint)" } }
  ]
 },
 "panels": [
  { "title": " ", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# API Observability" } },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(endpoint) (rate(robosystems_api_request_duration_seconds_bucket{endpoint=~\"$endpoints\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "stat",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(endpoint) (rate(robosystems_api_request_duration_seconds_bucket{endpoint=~\"$endpoints\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Volume",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "topk(15, sum by(endpoint) (rate(robosystems_api_requests_total{endpoint=~\"$endpoints\"}[5m]))) * 5",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Volume",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(robosystems_api_requests_total{endpoint=~\"$endpoints\"}[5m])) * 5",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status_code) (rate(robosystems_api_requests_total{endpoint=~\"$endpoints\"}[5m]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Total Business Events",
   "type": "stat",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(event_type) (rate(robosystems_business_events_total{endpoint=~\"$endpoints\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Business Events by Volume",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "avg by(event_type) (topk(15, rate(robosystems_business_events_total{endpoint=~\"$endpoints\"}[5m]))) * 5",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  { "title": " ", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 37 }, "options": { "content": "# Container Services" } },
  {
   "title": "Container CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "ClusterName": "robosystems-api-prod-cluster", "ServiceName": "robosystems-api-prod-service" },
     "label": "RoboSystems API",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": { "ServiceName": "roboledger-prod" },
     "label": "${PROP('Dim.ServiceName')}",
     "metricName": "CPUUtilization",
     "namespace": "AWS/AppRunner",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": { "ServiceName": "roboinvestor-prod" },
     "label": "${PROP('Dim.ServiceName')}",
     "metricName": "CPUUtilization",
     "namespace": "AWS/AppRunner",
     "period": "300",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "dimensions": { "ServiceName": "robosystems-app-prod" },
     "label": "${PROP('Dim.ServiceName')}",
     "metricName": "CPUUtilization",
     "namespace": "AWS/AppRunner",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Container Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "ClusterName": "robosystems-api-prod-cluster", "ServiceName": "robosystems-api-prod-service" },
     "label": "RoboSystems API",
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": { "ServiceName": "robosystems-app-prod" },
     "label": "${PROP('Dim.ServiceName')}",
     "metricName": "MemoryUtilization",
     "namespace": "AWS/AppRunner",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": { "ServiceName": "roboledger-prod" },
     "label": "${PROP('Dim.ServiceName')}",
     "metricName": "MemoryUtilization",
     "namespace": "AWS/AppRunner",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": { "ServiceName": "roboinvestor-prod" },
     "label": "${PROP('Dim.ServiceName')}",
     "metricName": "MemoryUtilization",
     "namespace": "AWS/AppRunner",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Dagster CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": {
      "ClusterName": "robosystems-dagster-prod-cluster"
     },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "ClusterName": "robosystems-dagster-prod-cluster",
      "TaskDefinitionFamily": "robosystems-dagster-run-prod"
     },
     "metricName": "CpuUtilized",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "ClusterName": "robosystems-dagster-prod-cluster",
      "TaskDefinitionFamily": "robosystems-dagster-run-prod"
     },
     "metricName": "CpuReserved",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Dagster Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": {
      "ClusterName": "robosystems-dagster-prod-cluster"
     },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": {
      "ClusterName": "robosystems-dagster-prod-cluster",
      "TaskDefinitionFamily": "robosystems-dagster-run-prod"
     },
     "metricName": "MemoryUtilized",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": {
      "ClusterName": "robosystems-dagster-prod-cluster",
      "TaskDefinitionFamily": "robosystems-dagster-run-prod"
     },
     "metricName": "MemoryReserved",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Dagster Task Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": {
      "ClusterName": "robosystems-dagster-prod-cluster"
     },
     "metricName": "TaskCount",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Dagster Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": {
      "ClusterName": "robosystems-dagster-prod-cluster",
      "TaskDefinitionFamily": "robosystems-dagster-daemon-prod"
     },
     "label": "Daemon Bytes In",
     "metricName": "NetworkRxBytes",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "ClusterName": "robosystems-dagster-prod-cluster",
      "TaskDefinitionFamily": "robosystems-dagster-webserver-prod"
     },
     "label": "Webserver Bytes In",
     "metricName": "NetworkRxBytes",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "ClusterName": "robosystems-dagster-prod-cluster",
      "TaskDefinitionFamily": "robosystems-dagster-run-prod"
     },
     "label": "Run Bytes In",
     "metricName": "NetworkRxBytes",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "ClusterName": "robosystems-dagster-prod-cluster",
      "TaskDefinitionFamily": "robosystems-dagster-daemon-prod"
     },
     "label": "Daemon Bytes Out",
     "metricName": "NetworkTxBytes",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "ClusterName": "robosystems-dagster-prod-cluster",
      "TaskDefinitionFamily": "robosystems-dagster-webserver-prod"
     },
     "label": "Webserver Bytes Out",
     "metricName": "NetworkTxBytes",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "ClusterName": "robosystems-dagster-prod-cluster",
      "TaskDefinitionFamily": "robosystems-dagster-run-prod"
     },
     "label": "Run Bytes Out",
     "metricName": "NetworkTxBytes",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": " ", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 69 }, "options": { "content": "# Graph Instances" } },
  {
   "title": "Graph CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "InstanceId": "*", "cpu": "cpu-total" },
     "metricName": "CPU_USAGE_ACTIVE",
     "namespace": "RoboSystems/Graph/prod",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "AutoScalingGroupName": "RoboSystemsGraphLadybugStandardProd-writers-asg"
     },
     "label": "Standard ASG",
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "AutoScalingGroupName": "RoboSystemsGraphLadybugSharedProd-writers-asg"
     },
     "label": "Shared ASG",
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Graph Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "metricName": "mem_used_percent",
     "namespace": "RoboSystems/Graph/prod",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Graph Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "metricName": "DISK_USED_PERCENT",
     "namespace": "RoboSystems/Graph/prod",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Graph Disk Used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "metricName": "disk_used",
     "namespace": "RoboSystems/Graph/prod",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Graph Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": { "InstanceId": "*", "name": "nvme1n1" },
     "metricName": "diskio_read_bytes",
     "namespace": "RoboSystems/Graph/prod",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": { "InstanceId": "*", "name": "nvme1n1" },
     "metricName": "diskio_write_bytes",
     "namespace": "RoboSystems/Graph/prod",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Graph Network Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": {
      "AutoScalingGroupName": "RoboSystemsGraphLadybugStandardProd-writers-asg"
     },
     "label": "Standard Network In",
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "AutoScalingGroupName": "RoboSystemsGraphLadybugStandardProd-writers-asg"
     },
     "label": "Standard Network Out",
     "metricName": "NetworkOut",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "AutoScalingGroupName": "RoboSystemsGraphLadybugSharedProd-writers-asg"
     },
     "label": "Shared Network In",
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "AutoScalingGroupName": "RoboSystemsGraphLadybugSharedProd-writers-asg"
     },
     "label": "Shared Network Out",
     "metricName": "NetworkOut",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Graph Instances by Tier",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "metricName": "InstancesByTier",
     "namespace": "RoboSystems/Graph/prod",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Minimum"
    }
   ]
  },
  {
   "title": "Graph Instances by Age",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "metricName": "InstancesByAge",
     "namespace": "RoboSystems/Graph/prod",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Minimum"
    }
   ]
  },
  {
   "title": "Graph Instance Utilization",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "metricName": "InstanceUtilization",
     "namespace": "RoboSystems/Graph/prod",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Minimum"
    }
   ]
  },
  {
   "title": "Graph Instance Available Slots",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "metricName": "InstanceAvailableSlots",
     "namespace": "RoboSystems/Graph/prod",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Minimum"
    }
   ]
  },
  {
   "title": "Graph Databases per Instance",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "metricName": "InstanceDatabaseCount",
     "namespace": "RoboSystems/Graph/prod",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Minimum"
    }
   ]
  },
  {
   "title": "Graph Volume Actions",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "metricName": "VolumeMonitorErrors",
     "namespace": "RoboSystems/Graph/prod",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "metricName": "VolumeMonitorExecutions",
     "namespace": "RoboSystems/Graph/prod",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "metricName": "VolumesExpanded",
     "namespace": "RoboSystems/Graph/prod",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "metricName": "OrphanedVolumes",
     "namespace": "RoboSystems/Graph/prod",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  { "title": " ", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 124 }, "options": { "content": "# RDS Postgres" } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "robosystems-prod" },
     "label": "CPU Utilization",
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "robosystems-prod" },
     "label": "Free Memory",
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Free Storage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "robosystems-prod" },
     "label": "Free Storage Space",
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPU Credit Balances",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "robosystems-prod" },
     "label": "CPU Credit Balance",
     "metricName": "CPUCreditBalance",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "robosystems-prod" },
     "label": "CPU Surplus Credit Balance",
     "metricName": "CPUSurplusCreditBalance",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "robosystems-prod" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "robosystems-prod" },
     "metricName": "SwapUsage",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Read / Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "robosystems-prod" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "robosystems-prod" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Read / Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "robosystems-prod" },
     "metricName": "ReadThroughput",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "robosystems-prod" },
     "metricName": "WriteThroughput",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "robosystems-prod" },
     "label": "Bytes In",
     "metricName": "NetworkReceiveThroughput",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "robosystems-prod" },
     "label": "Bytes Out",
     "metricName": "NetworkTransmitThroughput",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  { "title": " ", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 157 }, "options": { "content": "# ElastiCache Valkey" } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "robosystems-prod-valkey-001" },
     "label": "CPU Utilization",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ElastiCache",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "robosystems-prod-valkey-001" },
     "metricName": "DatabaseMemoryUsagePercentage",
     "namespace": "AWS/ElastiCache",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Bytes Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "robosystems-prod-valkey-001" },
     "metricName": "BytesUsedForCache",
     "namespace": "AWS/ElastiCache",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPU Credit Balance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "robosystems-prod-valkey-001" },
     "metricName": "CPUCreditBalance",
     "namespace": "AWS/ElastiCache",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "robosystems-prod-valkey-001" },
     "label": "Connections",
     "metricName": "CurrConnections",
     "namespace": "AWS/ElastiCache",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "robosystems-prod-valkey-001" },
     "metricName": "SwapUsage",
     "namespace": "AWS/ElastiCache",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Evictions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "robosystems-prod-valkey-001" },
     "metricName": "Evictions",
     "namespace": "AWS/ElastiCache",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Cache Hits / Misses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "robosystems-prod-valkey-001" },
     "metricName": "CacheHits",
     "namespace": "AWS/ElastiCache",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": { "CacheClusterId": "robosystems-prod-valkey-001" },
     "metricName": "CacheMisses",
     "namespace": "AWS/ElastiCache",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "robosystems-prod-valkey-001" },
     "label": "Bytes In",
     "metricName": "NetworkBytesIn",
     "namespace": "AWS/ElastiCache",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    },
    {
     "dimensions": { "CacheClusterId": "robosystems-prod-valkey-001" },
     "label": "Bytes Out",
     "metricName": "NetworkBytesOut",
     "namespace": "AWS/ElastiCache",
     "period": "300",
     "queryMode": "Metrics",
     "region": "${aws_region}",
     "statistic": "Average"
    }
   ]
  }
 ]
}