"""add on delete cascade to documents graph_id fk

Revision ID: 0764cf42eac6
Revises: ff27f43e5f7f
Create Date: 2026-07-10 16:05:26.958118

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "0764cf42eac6"
down_revision = "ff27f43e5f7f"
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_constraint(op.f("documents_graph_id_fkey"), "documents", type_="foreignkey")
  op.create_foreign_key(
    "documents_graph_id_fkey",
    "documents",
    "graphs",
    ["graph_id"],
    ["graph_id"],
    ondelete="CASCADE",
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_constraint("documents_graph_id_fkey", "documents", type_="foreignkey")
  op.create_foreign_key(
    "documents_graph_id_fkey",
    "documents",
    "graphs",
    ["graph_id"],
    ["graph_id"],
  )
  # ### end Alembic commands ###
