"""make password hash nullable and add external id to users

Prepares the users table for IdP-governed accounts (enterprise SSO + SCIM):

- ``password_hash`` becomes nullable. A NULL hash marks an account that can
  never password-login; the login, password-change, and password-reset flows
  all refuse a falsy/NULL hash, so no password can be bootstrapped onto such
  an account.
- ``external_id`` (nullable, indexed) carries the SCIM ``externalId`` the IdP
  round-trips. A non-null value is the provenance marker that the OIDC
  email-match link step gates on.

Downgrade note: restoring NOT NULL fails if any NULL-hash rows exist by then
(i.e. after SCIM provisioning has run). That is deliberate — downgrading past
this revision on a deployment with IdP-governed users would corrupt them.

Revision ID: 2bacd07cab13
Revises: 2eae4a0ad7ef
Create Date: 2026-08-11 22:29:15.227824

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2bacd07cab13"
down_revision = "2eae4a0ad7ef"
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column("users", sa.Column("external_id", sa.String(), nullable=True))
  op.alter_column("users", "password_hash", existing_type=sa.VARCHAR(), nullable=True)
  op.create_index(op.f("ix_users_external_id"), "users", ["external_id"], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f("ix_users_external_id"), table_name="users")
  op.alter_column("users", "password_hash", existing_type=sa.VARCHAR(), nullable=False)
  op.drop_column("users", "external_id")
  # ### end Alembic commands ###
