"""add oauth clients grants and tokens

Revision ID: 39c73ea18599
Revises: 8c8e469f4a0a
Create Date: 2026-08-25 23:48:11.582708

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "39c73ea18599"
down_revision = "8c8e469f4a0a"
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "oauth_clients",
    sa.Column("id", sa.String(), nullable=False),
    sa.Column("client_id", sa.String(), nullable=False),
    sa.Column("client_secret_hash", sa.String(length=64), nullable=True),
    sa.Column("client_name", sa.String(), nullable=False),
    sa.Column("redirect_uris", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("registration_source", sa.String(length=20), nullable=False),
    sa.Column("token_endpoint_auth_method", sa.String(length=32), nullable=False),
    sa.Column("client_uri", sa.String(), nullable=True),
    sa.Column("logo_uri", sa.String(), nullable=True),
    sa.Column("scope", sa.String(), nullable=True),
    sa.Column("is_trusted", sa.Boolean(), nullable=False),
    sa.Column("is_active", sa.Boolean(), nullable=False),
    sa.Column("registration_ip", sa.String(length=45), nullable=True),
    sa.Column("expires_at", sa.DateTime(), nullable=True),
    sa.Column("last_used_at", sa.DateTime(), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(
    "idx_oauth_clients_source_created",
    "oauth_clients",
    ["registration_source", "created_at"],
    unique=False,
  )
  op.create_index(
    op.f("ix_oauth_clients_client_id"), "oauth_clients", ["client_id"], unique=True
  )
  op.create_table(
    "oauth_grants",
    sa.Column("id", sa.String(), nullable=False),
    sa.Column("user_id", sa.String(), nullable=False),
    sa.Column("oauth_client_id", sa.String(), nullable=False),
    sa.Column("graph_id", sa.String(), nullable=False),
    sa.Column("resource", sa.String(), nullable=False),
    sa.Column("scope", sa.String(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("last_used_at", sa.DateTime(), nullable=True),
    sa.Column("revoked_at", sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(
      ["oauth_client_id"],
      ["oauth_clients.id"],
    ),
    sa.ForeignKeyConstraint(
      ["user_id"],
      ["users.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(
    "idx_oauth_grants_user_client",
    "oauth_grants",
    ["user_id", "oauth_client_id"],
    unique=False,
  )
  op.create_index(
    "idx_oauth_grants_user_revoked",
    "oauth_grants",
    ["user_id", "revoked_at"],
    unique=False,
  )
  op.create_index(
    op.f("ix_oauth_grants_graph_id"), "oauth_grants", ["graph_id"], unique=False
  )
  op.create_index(
    op.f("ix_oauth_grants_oauth_client_id"),
    "oauth_grants",
    ["oauth_client_id"],
    unique=False,
  )
  op.create_table(
    "oauth_tokens",
    sa.Column("id", sa.String(), nullable=False),
    sa.Column("grant_id", sa.String(), nullable=False),
    sa.Column("user_id", sa.String(), nullable=False),
    sa.Column("token_type", sa.String(length=8), nullable=False),
    sa.Column("token_hash", sa.String(length=64), nullable=False),
    sa.Column("prefix", sa.String(length=8), nullable=False),
    sa.Column("family_id", sa.String(), nullable=False),
    sa.Column("expires_at", sa.DateTime(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("last_used_at", sa.DateTime(), nullable=True),
    sa.Column("used_at", sa.DateTime(), nullable=True),
    sa.Column("revoked_at", sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(
      ["grant_id"],
      ["oauth_grants.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(
    "idx_oauth_tokens_expires", "oauth_tokens", ["expires_at"], unique=False
  )
  op.create_index(
    "idx_oauth_tokens_family_type",
    "oauth_tokens",
    ["family_id", "token_type"],
    unique=False,
  )
  op.create_index(
    "idx_oauth_tokens_user_type",
    "oauth_tokens",
    ["user_id", "token_type"],
    unique=False,
  )
  op.create_index(
    op.f("ix_oauth_tokens_grant_id"), "oauth_tokens", ["grant_id"], unique=False
  )
  op.create_index(
    op.f("ix_oauth_tokens_token_hash"), "oauth_tokens", ["token_hash"], unique=True
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f("ix_oauth_tokens_token_hash"), table_name="oauth_tokens")
  op.drop_index(op.f("ix_oauth_tokens_grant_id"), table_name="oauth_tokens")
  op.drop_index("idx_oauth_tokens_user_type", table_name="oauth_tokens")
  op.drop_index("idx_oauth_tokens_family_type", table_name="oauth_tokens")
  op.drop_index("idx_oauth_tokens_expires", table_name="oauth_tokens")
  op.drop_table("oauth_tokens")
  op.drop_index(op.f("ix_oauth_grants_oauth_client_id"), table_name="oauth_grants")
  op.drop_index(op.f("ix_oauth_grants_graph_id"), table_name="oauth_grants")
  op.drop_index("idx_oauth_grants_user_revoked", table_name="oauth_grants")
  op.drop_index("idx_oauth_grants_user_client", table_name="oauth_grants")
  op.drop_table("oauth_grants")
  op.drop_index(op.f("ix_oauth_clients_client_id"), table_name="oauth_clients")
  op.drop_index("idx_oauth_clients_source_created", table_name="oauth_clients")
  op.drop_table("oauth_clients")
  # ### end Alembic commands ###
