"""add graph scope to user api keys

Revision ID: 506bb56c5347
Revises: 7bedebbeefb6
Create Date: 2026-08-05 13:56:35.806462

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "506bb56c5347"
down_revision = "7bedebbeefb6"
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column("user_api_keys", sa.Column("graph_id", sa.String(), nullable=True))
  op.create_index(
    op.f("ix_user_api_keys_graph_id"), "user_api_keys", ["graph_id"], unique=False
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f("ix_user_api_keys_graph_id"), table_name="user_api_keys")
  op.drop_column("user_api_keys", "graph_id")
  # ### end Alembic commands ###
