"""org invitations

Revision ID: 50dae0508279
Revises: dbd59303e73c
Create Date: 2026-08-02 21:45:30.578404

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "50dae0508279"
down_revision = "dbd59303e73c"
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "org_invitations",
    sa.Column("id", sa.String(), nullable=False),
    sa.Column("org_id", sa.String(), nullable=False),
    sa.Column("email", sa.String(), nullable=False),
    # Reference the existing orgrole enum (created with org_users) without
    # attempting to CREATE TYPE again.
    sa.Column(
      "role",
      postgresql.ENUM("OWNER", "ADMIN", "MEMBER", name="orgrole", create_type=False),
      nullable=False,
    ),
    sa.Column("graph_grants", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("invited_by", sa.String(), nullable=False),
    sa.Column("token_hash", sa.String(), nullable=False),
    sa.Column("status", sa.String(length=20), nullable=False),
    sa.Column("expires_at", sa.DateTime(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("accepted_at", sa.DateTime(), nullable=True),
    sa.Column("revoked_at", sa.DateTime(), nullable=True),
    sa.Column("accepted_user_id", sa.String(), nullable=True),
    sa.ForeignKeyConstraint(
      ["accepted_user_id"],
      ["users.id"],
    ),
    sa.ForeignKeyConstraint(
      ["invited_by"],
      ["users.id"],
    ),
    sa.ForeignKeyConstraint(
      ["org_id"],
      ["orgs.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(
    op.f("ix_org_invitations_email"), "org_invitations", ["email"], unique=False
  )
  op.create_index(
    op.f("ix_org_invitations_org_id"), "org_invitations", ["org_id"], unique=False
  )
  op.create_index(
    op.f("ix_org_invitations_token_hash"),
    "org_invitations",
    ["token_hash"],
    unique=True,
  )
  op.create_index(
    "uq_org_invitations_pending_email",
    "org_invitations",
    ["org_id", "email"],
    unique=True,
    postgresql_where=sa.text("status = 'pending'"),
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(
    "uq_org_invitations_pending_email",
    table_name="org_invitations",
    postgresql_where=sa.text("status = 'pending'"),
  )
  op.drop_index(op.f("ix_org_invitations_token_hash"), table_name="org_invitations")
  op.drop_index(op.f("ix_org_invitations_org_id"), table_name="org_invitations")
  op.drop_index(op.f("ix_org_invitations_email"), table_name="org_invitations")
  op.drop_table("org_invitations")
  # ### end Alembic commands ###
