"""add graph_stale_since to graphs

Revision ID: 62bc724a250a
Revises: f968e3bf1f52
Create Date: 2026-10-04 22:02:15.349603

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "62bc724a250a"
down_revision = "f968e3bf1f52"
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column("graphs", sa.Column("graph_stale_since", sa.DateTime(), nullable=True))
  # ### end Alembic commands ###
  # A graph stale today is owed its first-write time; the latest is the
  # closest value on record.
  op.execute(
    "UPDATE graphs SET graph_stale_since = graph_stale_at "
    "WHERE graph_stale AND graph_stale_since IS NULL"
  )


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column("graphs", "graph_stale_since")
  # ### end Alembic commands ###
