"""stop using graphs graph_instance_id

Revision ID: 6ef007fe2091
Revises: 62bc724a250a
Create Date: 2026-10-04 23:26:41.356712

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6ef007fe2091"
down_revision = "62bc724a250a"
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column(
    "graphs", "graph_instance_id", existing_type=sa.VARCHAR(), nullable=True
  )
  op.drop_index(op.f("idx_graphs_instance"), table_name="graphs")
  op.drop_index(op.f("ix_graphs_graph_instance_id"), table_name="graphs")
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_index(
    op.f("ix_graphs_graph_instance_id"), "graphs", ["graph_instance_id"], unique=False
  )
  op.create_index(
    op.f("idx_graphs_instance"), "graphs", ["graph_instance_id"], unique=False
  )
  # Rows created after the upgrade carry no value; the old column default.
  op.execute(
    "UPDATE graphs SET graph_instance_id = 'default' WHERE graph_instance_id IS NULL"
  )
  op.alter_column(
    "graphs", "graph_instance_id", existing_type=sa.VARCHAR(), nullable=False
  )
  # ### end Alembic commands ###
