"""add mcp mutation audit

Revision ID: 73bbbb0e0593
Revises: 39c73ea18599
Create Date: 2026-09-27 23:45:13.178706

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "73bbbb0e0593"
down_revision = "39c73ea18599"
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "mcp_mutation_audit",
    sa.Column("id", sa.String(), nullable=False),
    sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("duration_ms", sa.Float(), nullable=False),
    sa.Column("graph_id", sa.String(), nullable=False),
    sa.Column("org_id", sa.String(), nullable=True),
    sa.Column("user_id", sa.String(), nullable=True),
    sa.Column("tool_name", sa.String(), nullable=False),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("error_code", sa.String(), nullable=True),
    sa.Column("surface", sa.String(), nullable=False),
    sa.Column("caller_kind", sa.String(), nullable=False),
    sa.Column("auth_method", sa.String(), nullable=True),
    sa.Column("api_key_prefix", sa.String(), nullable=True),
    sa.Column("request_id", sa.String(), nullable=True),
    sa.Column("operator_type", sa.String(), nullable=True),
    sa.Column("operation_id", sa.String(), nullable=True),
    sa.Column("arguments_sha256", sa.String(length=64), nullable=False),
    sa.Column("object_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(
    "idx_mcp_mutation_audit_graph_time",
    "mcp_mutation_audit",
    ["graph_id", "occurred_at"],
    unique=False,
  )
  op.create_index(
    "idx_mcp_mutation_audit_operation",
    "mcp_mutation_audit",
    ["operation_id"],
    unique=False,
  )
  op.create_index(
    "idx_mcp_mutation_audit_time", "mcp_mutation_audit", ["occurred_at"], unique=False
  )
  op.create_index(
    "idx_mcp_mutation_audit_user_time",
    "mcp_mutation_audit",
    ["user_id", "occurred_at"],
    unique=False,
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index("idx_mcp_mutation_audit_user_time", table_name="mcp_mutation_audit")
  op.drop_index("idx_mcp_mutation_audit_time", table_name="mcp_mutation_audit")
  op.drop_index("idx_mcp_mutation_audit_operation", table_name="mcp_mutation_audit")
  op.drop_index("idx_mcp_mutation_audit_graph_time", table_name="mcp_mutation_audit")
  op.drop_table("mcp_mutation_audit")
  # ### end Alembic commands ###
