"""add user passkeys and mfa recovery codes

Two tables for passkey MFA (WebAuthn):

- user_passkeys: one row per enrolled authenticator. Public-key material
  only (COSE bytes) — WebAuthn stores no server-side secret, so there is no
  encryption-key decision here. credential_id is base64url-unpadded and
  unique; BE/BS flags distinguish synced from device-bound credentials.
- user_mfa_recovery_codes: SHA-256 hashes of single-use backstop codes,
  replaced as a set on regeneration. Deliberately not a user_tokens variant
  (that model enforces one live token per type per user).

Deploys dark: PASSKEYS_ENABLED defaults false and nothing writes these
tables until the passkey surface mounts.

Revision ID: 7fd78cf16c54
Revises: af54a36c04b9
Create Date: 2026-08-12 19:20:20.046203

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7fd78cf16c54"
down_revision = "af54a36c04b9"
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "user_mfa_recovery_codes",
    sa.Column("id", sa.String(), nullable=False),
    sa.Column("user_id", sa.String(), nullable=False),
    sa.Column("code_hash", sa.String(length=64), nullable=False),
    sa.Column("used_at", sa.DateTime(), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(
      ["user_id"],
      ["users.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(
    op.f("ix_user_mfa_recovery_codes_code_hash"),
    "user_mfa_recovery_codes",
    ["code_hash"],
    unique=False,
  )
  op.create_index(
    op.f("ix_user_mfa_recovery_codes_user_id"),
    "user_mfa_recovery_codes",
    ["user_id"],
    unique=False,
  )
  op.create_table(
    "user_passkeys",
    sa.Column("id", sa.String(), nullable=False),
    sa.Column("user_id", sa.String(), nullable=False),
    sa.Column("credential_id", sa.String(), nullable=False),
    sa.Column("public_key", sa.LargeBinary(), nullable=False),
    sa.Column("sign_count", sa.Integer(), nullable=False),
    sa.Column("transports", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("aaguid", sa.String(), nullable=True),
    sa.Column("backup_eligible", sa.Boolean(), nullable=False),
    sa.Column("backup_state", sa.Boolean(), nullable=False),
    sa.Column("name", sa.String(length=100), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("last_used_at", sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(
      ["user_id"],
      ["users.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(
    op.f("ix_user_passkeys_credential_id"),
    "user_passkeys",
    ["credential_id"],
    unique=True,
  )
  op.create_index(
    op.f("ix_user_passkeys_user_id"), "user_passkeys", ["user_id"], unique=False
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f("ix_user_passkeys_user_id"), table_name="user_passkeys")
  op.drop_index(op.f("ix_user_passkeys_credential_id"), table_name="user_passkeys")
  op.drop_table("user_passkeys")
  op.drop_index(
    op.f("ix_user_mfa_recovery_codes_user_id"), table_name="user_mfa_recovery_codes"
  )
  op.drop_index(
    op.f("ix_user_mfa_recovery_codes_code_hash"), table_name="user_mfa_recovery_codes"
  )
  op.drop_table("user_mfa_recovery_codes")
  # ### end Alembic commands ###
