"""add live subscription uniqueness per user and resource

Revision ID: 8c8e469f4a0a
Revises: a40f29cc6fe7
Create Date: 2026-08-25 19:45:20.398341

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "8c8e469f4a0a"
down_revision = "a40f29cc6fe7"
branch_labels = None
depends_on = None


def upgrade() -> None:
  # One live subscription per (resource, subscriber): repository access is per
  # user, and the router's check-then-insert raced. Graph rows carry no user_id
  # and checkout rows carry no resource_id until provisioning, so the WHERE
  # keeps both outside the constraint.
  #
  # Pre-deploy check (the index build fails, and with it the daemon boot, if
  # duplicate live rows already exist):
  #   SELECT resource_type, resource_id, user_id, count(*)
  #   FROM billing_subscriptions
  #   WHERE status NOT IN ('canceled', 'failed')
  #     AND resource_id IS NOT NULL AND user_id IS NOT NULL
  #   GROUP BY 1, 2, 3 HAVING count(*) > 1;
  # Any row returned is a duplicate to resolve by hand first (cancel the
  # stray at the provider, then locally).
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_index(
    "uq_billing_sub_live_user_resource",
    "billing_subscriptions",
    ["resource_type", "resource_id", "user_id"],
    unique=True,
    postgresql_where="status NOT IN ('canceled', 'failed') AND resource_id IS NOT NULL AND user_id IS NOT NULL",
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(
    "uq_billing_sub_live_user_resource",
    table_name="billing_subscriptions",
    postgresql_where="status NOT IN ('canceled', 'failed') AND resource_id IS NOT NULL AND user_id IS NOT NULL",
  )
  # ### end Alembic commands ###
