"""add taxonomy_pin to graphs

Revision ID: a1ff04a7926e
Revises: 366a6659343d
Create Date: 2026-04-19 18:13:29.514496

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a1ff04a7926e"
down_revision = "366a6659343d"
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column(
    "graphs",
    sa.Column("taxonomy_pin", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column("graphs", "taxonomy_pin")
  # ### end Alembic commands ###
