"""add user identities and scim tokens

Two tables for enterprise SSO + SCIM (flags default false; nothing consumes
these until the OIDC/SCIM surfaces mount):

- ``user_identities`` — links a local user to an IdP subject. Written at the
  first successful OIDC login; ``(issuer, subject)`` is the login lookup, and
  the ``(user_id, issuer)`` uniqueness keeps one identity per issuer per user.
- ``scim_tokens`` — org-scoped bearer credentials the customer's IdP presents
  to the SCIM surface. Stores bcrypt hash + SHA-256 lookup fingerprint (the
  UserAPIKey pattern); plaintext exists only at mint.

Revision ID: af54a36c04b9
Revises: 2bacd07cab13
Create Date: 2026-08-11 22:29:38.249013

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "af54a36c04b9"
down_revision = "2bacd07cab13"
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "scim_tokens",
    sa.Column("id", sa.String(), nullable=False),
    sa.Column("org_id", sa.String(), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("token_hash", sa.String(), nullable=False),
    sa.Column("key_fingerprint", sa.String(length=64), nullable=False),
    sa.Column("prefix", sa.String(), nullable=False),
    sa.Column("is_active", sa.Boolean(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("last_used_at", sa.DateTime(), nullable=True),
    sa.Column("expires_at", sa.DateTime(), nullable=True),
    sa.Column("revoked_at", sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(
      ["org_id"],
      ["orgs.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("token_hash"),
  )
  op.create_index(
    op.f("ix_scim_tokens_key_fingerprint"),
    "scim_tokens",
    ["key_fingerprint"],
    unique=True,
  )
  op.create_index(
    op.f("ix_scim_tokens_org_id"), "scim_tokens", ["org_id"], unique=False
  )
  op.create_table(
    "user_identities",
    sa.Column("id", sa.String(), nullable=False),
    sa.Column("user_id", sa.String(), nullable=False),
    sa.Column("provider_type", sa.String(length=20), nullable=False),
    sa.Column("issuer", sa.String(), nullable=False),
    sa.Column("subject", sa.String(), nullable=False),
    sa.Column("email_at_link", sa.String(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("last_login_at", sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(
      ["user_id"],
      ["users.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("issuer", "subject", name="uq_user_identity_issuer_subject"),
    sa.UniqueConstraint("user_id", "issuer", name="uq_user_identity_user_issuer"),
  )
  op.create_index(
    op.f("ix_user_identities_issuer"), "user_identities", ["issuer"], unique=False
  )
  op.create_index(
    op.f("ix_user_identities_user_id"), "user_identities", ["user_id"], unique=False
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f("ix_user_identities_user_id"), table_name="user_identities")
  op.drop_index(op.f("ix_user_identities_issuer"), table_name="user_identities")
  op.drop_table("user_identities")
  op.drop_index(op.f("ix_scim_tokens_org_id"), table_name="scim_tokens")
  op.drop_index(op.f("ix_scim_tokens_key_fingerprint"), table_name="scim_tokens")
  op.drop_table("scim_tokens")
  # ### end Alembic commands ###
