"""add file columns to documents

Revision ID: b82af6e126c8
Revises: d91b0a7f3925
Create Date: 2026-10-09 21:08:42.068011

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b82af6e126c8"
down_revision = "d91b0a7f3925"
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column("documents", sa.Column("file_s3_key", sa.String(), nullable=True))
  op.add_column(
    "documents", sa.Column("file_name", sa.String(length=255), nullable=True)
  )
  op.add_column(
    "documents", sa.Column("file_content_type", sa.String(length=100), nullable=True)
  )
  op.add_column(
    "documents", sa.Column("file_size_bytes", sa.BigInteger(), nullable=True)
  )
  op.add_column(
    "documents", sa.Column("file_sha256", sa.String(length=64), nullable=True)
  )
  op.add_column(
    "documents", sa.Column("file_status", sa.String(length=20), nullable=True)
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column("documents", "file_status")
  op.drop_column("documents", "file_sha256")
  op.drop_column("documents", "file_size_bytes")
  op.drop_column("documents", "file_content_type")
  op.drop_column("documents", "file_name")
  op.drop_column("documents", "file_s3_key")
  # ### end Alembic commands ###
