"""add auto_dispatch_obligations to graphs for stream 2e

Revision ID: bf7ed6db5eff
Revises: a1ff04a7926e
Create Date: 2026-04-24 23:23:20.021176

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bf7ed6db5eff"
down_revision = "a1ff04a7926e"
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column(
    "graphs", sa.Column("auto_dispatch_obligations", sa.Boolean(), nullable=True)
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column("graphs", "auto_dispatch_obligations")
  # ### end Alembic commands ###
