"""phase 5 add connections.last_cdc_watermark

Revision ID: d528e24fb069
Revises: f06051a09081
Create Date: 2026-05-19 23:07:56.490685

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d528e24fb069"
down_revision = "f06051a09081"
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column(
    "connections", sa.Column("last_cdc_watermark", sa.DateTime(), nullable=True)
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column("connections", "last_cdc_watermark")
  # ### end Alembic commands ###
