"""drop graphs graph_instance_id

Revision ID: d91b0a7f3925
Revises: 7f11ce866e16
Create Date: 2026-10-05 12:16:57.080476

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d91b0a7f3925"
down_revision = "7f11ce866e16"
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column("graphs", "graph_instance_id")
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column(
    "graphs",
    sa.Column("graph_instance_id", sa.VARCHAR(), autoincrement=False, nullable=True),
  )
  # ### end Alembic commands ###
