"""add connections source_name for external providers

Revision ID: dbd59303e73c
Revises: 0764cf42eac6
Create Date: 2026-07-30 12:17:38.746183

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dbd59303e73c"
down_revision = "0764cf42eac6"
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column("connections", sa.Column("source_name", sa.String(), nullable=True))
  op.create_index(
    "uq_connections_graph_source_name",
    "connections",
    ["graph_id", "source_name"],
    unique=True,
    postgresql_where="source_name IS NOT NULL AND deleted_at IS NULL",
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(
    "uq_connections_graph_source_name",
    table_name="connections",
    postgresql_where="source_name IS NOT NULL AND deleted_at IS NULL",
  )
  op.drop_column("connections", "source_name")
  # ### end Alembic commands ###
