"""add invoice sync fields

Revision ID: f599c98cf98c
Revises: c7cf00620afb
Create Date: 2026-02-12 20:11:30.491372

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f599c98cf98c"
down_revision = "c7cf00620afb"
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column(
    "billing_invoices", sa.Column("invoice_pdf", sa.String(), nullable=True)
  )
  op.add_column(
    "billing_invoices", sa.Column("hosted_invoice_url", sa.String(), nullable=True)
  )
  op.add_column(
    "billing_invoices",
    sa.Column("currency", sa.String(), server_default="usd", nullable=False),
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column("billing_invoices", "currency")
  op.drop_column("billing_invoices", "hosted_invoice_url")
  op.drop_column("billing_invoices", "invoice_pdf")
  # ### end Alembic commands ###
