"""add operation mutation audit

Revision ID: f968e3bf1f52
Revises: 39c73ea18599
Create Date: 2026-09-28 00:31:46.893227

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f968e3bf1f52"
down_revision = "39c73ea18599"
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "operation_mutation_audit",
    sa.Column("id", sa.String(), nullable=False),
    sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("duration_ms", sa.Float(), nullable=False),
    sa.Column("graph_id", sa.String(), nullable=False),
    sa.Column("org_id", sa.String(), nullable=True),
    sa.Column("user_id", sa.String(), nullable=True),
    sa.Column("surface", sa.String(), nullable=False),
    sa.Column("operation_name", sa.String(), nullable=False),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("error_code", sa.String(), nullable=True),
    sa.Column("auth_method", sa.String(), nullable=True),
    sa.Column("api_key_prefix", sa.String(), nullable=True),
    sa.Column("request_id", sa.String(), nullable=True),
    sa.Column("operation_id", sa.String(), nullable=True),
    sa.Column("operator_type", sa.String(), nullable=True),
    sa.Column("arguments_fingerprint", sa.String(length=64), nullable=True),
    sa.Column("object_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(
    "idx_operation_mutation_audit_graph_time",
    "operation_mutation_audit",
    ["graph_id", "occurred_at"],
    unique=False,
  )
  op.create_index(
    "idx_operation_mutation_audit_operation",
    "operation_mutation_audit",
    ["operation_id"],
    unique=False,
  )
  op.create_index(
    "idx_operation_mutation_audit_time",
    "operation_mutation_audit",
    ["occurred_at"],
    unique=False,
  )
  op.create_index(
    "idx_operation_mutation_audit_user_time",
    "operation_mutation_audit",
    ["user_id", "occurred_at"],
    unique=False,
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(
    "idx_operation_mutation_audit_user_time", table_name="operation_mutation_audit"
  )
  op.drop_index(
    "idx_operation_mutation_audit_time", table_name="operation_mutation_audit"
  )
  op.drop_index(
    "idx_operation_mutation_audit_operation", table_name="operation_mutation_audit"
  )
  op.drop_index(
    "idx_operation_mutation_audit_graph_time", table_name="operation_mutation_audit"
  )
  op.drop_table("operation_mutation_audit")
  # ### end Alembic commands ###
