"""drop graphs reporting_style_id moved to entity

Revision ID: ff27f43e5f7f
Revises: d528e24fb069
Create Date: 2026-07-10 01:15:29.342863

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ff27f43e5f7f"
down_revision = "d528e24fb069"
branch_labels = None
depends_on = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f("idx_graphs_reporting_style"), table_name="graphs")
  op.drop_column("graphs", "reporting_style_id")
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column(
    "graphs",
    sa.Column(
      "reporting_style_id",
      sa.VARCHAR(),
      server_default=sa.text(
        "'025f5d48-12ce-5d65-b9eb-4f137a10ef06'::character varying"
      ),
      autoincrement=False,
      nullable=False,
    ),
  )
  op.create_index(
    op.f("idx_graphs_reporting_style"), "graphs", ["reporting_style_id"], unique=False
  )
  # ### end Alembic commands ###
